<?php
/** Instrucciones breves para los juegos propios que no traen ayuda en su CFG. */
defined( 'ABSPATH' ) || exit;
return array(
	'2048-classic'       => 'Desliza o usa las flechas para mover todas las fichas. Dos fichas iguales se suman al chocar: llega a 2048 sin llenar el tablero.',
	'2048-hex'           => 'Desliza en seis direcciones para juntar fichas iguales en el tablero hexagonal. Cada unión suma puntos; no dejes que se llene.',
	'air-hockey'         => 'Arrastra tu mazo para golpear el disco y marcar en la portería rival. Gana el primero en llegar a 7 goles.',
	'battle-grid'        => 'Coloca tu flota y dispara tocando casillas del radar enemigo. Hunde todos sus barcos antes de que él hunda los tuyos.',
	'bowling-flick'      => 'Desliza hacia los bolos para lanzar: la dirección marca el rumbo y la curva final da efecto. Diez frames con puntuación oficial.',
	'brick-breaker-dx'   => 'Mueve la pala con el dedo, el ratón o las flechas para devolver la bola y romper todos los ladrillos. Recoge las mejoras que caen.',
	'checkers'           => 'Toca una ficha y después la casilla de destino. Captura saltando en diagonal (es obligatorio) y corona llegando al fondo.',
	'color-sort'         => 'Toca un tubo para coger la bola de arriba y otro para soltarla sobre una del mismo color o en un tubo vacío. Deja cada tubo de un solo color.',
	'crystal-labyrinth'  => 'Avanza y gira con las flechas o el mando táctil. Recoge los cristales y encuentra el portal antes de que se acabe el aceite del farol.',
	'cube-roller'        => 'Haz rodar el bloque con las flechas o deslizando. Llévalo de pie hasta el agujero de salida sin caer por los bordes.',
	'cut-and-drop'       => 'Toca para soltar cada bloque sobre la torre. La parte que sobresale se corta: apila con precisión para llegar más alto.',
	'darts-pro'          => 'Apunta arrastrando y suelta para lanzar. Partida de 501: baja a cero exacto y cierra con un doble o con la diana.',
	'dice-poker'         => 'Tira los cinco dados, toca los que quieras guardar y vuelve a tirar hasta dos veces. Consigue la mejor jugada del póker de dados.',
	'drone-flight'       => 'Mantén pulsado para subir y suelta para bajar. Guía el dron entre los obstáculos sin tocar las paredes.',
	'flow-lines'         => 'Arrastra desde un punto hasta su pareja del mismo color. Une todas las parejas y llena el tablero sin cruzar caminos.',
	'frog-crossing'      => 'Desliza o usa las flechas para saltar. Cruza la carretera y el río sobre troncos y tortugas hasta llegar a las casillas de la orilla.',
	'hex-defense'        => 'Toca una casilla libre para construir torres y mejóralas con las monedas que ganas. Detén todas las oleadas antes de que lleguen a tu base.',
	'hex-skirmish'       => 'Toca una unidad para ver dónde puede moverse o atacar y toca el destino. Derrota al ejército rival por turnos.',
	'home-run-derby'     => 'Toca en el momento justo para batear. Cuanto más centrado el golpe, más lejos vuela la bola: busca el home run.',
	'hoop-arc'           => 'Desliza hacia la canasta para lanzar; la fuerza del gesto decide la parábola. Encadena canastas para ganar más puntos.',
	'ice-pusher'         => 'Empuja las cajas sobre el hielo: se deslizan hasta chocar. Colócalas todas en su sitio con el menor número de movimientos.',
	'jewel-swap'         => 'Intercambia dos gemas vecinas para alinear tres o más del mismo color. Encadena combos para sumar más puntos.',
	'jewel-tide'         => 'Intercambia gemas vecinas para hacer líneas de tres o más antes de que suba la marea. Los combos te dan tiempo extra.',
	'laser-mirrors'      => 'Toca los espejos para girarlos y guiar el láser hasta todos los objetivos del nivel.',
	'lunar-lander'       => 'Usa los propulsores para frenar la caída y corregir la inclinación. Aterriza suave y recto en una plataforma plana sin quedarte sin combustible.',
	'mahjong-solitaire'  => 'Toca dos fichas iguales que estén libres (sin nada encima ni a ambos lados) para retirarlas. Vacía el tablero.',
	'marble-roll'        => 'Inclina el tablero con las flechas o arrastrando para llevar la canica a la meta sin que caiga en los agujeros.',
	'maze-defense'       => 'Coloca torres para formar un laberinto y alargar el camino de los enemigos. Que no llegue ninguno a la salida.',
	'micro-tactics'      => 'Selecciona tus unidades, muévelas y ataca por turnos. Aprovecha el terreno y acaba con las tropas enemigas.',
	'mini-golf-3d'       => 'Arrastra hacia atrás para apuntar y elegir fuerza, y suelta para golpear. Mete la bola en el hoyo con los menos golpes posibles.',
	'missile-guard'      => 'Toca el cielo para lanzar una contramedida que explote en ese punto. Protege las ciudades de los misiles que caen.',
	'neon-paddle'        => 'Arrastra o usa ↑ ↓ para mover tu pala y devolver la bola. Gana el primero en llegar a 7 puntos.',
	'nonogram-daily'     => 'Usa los números de filas y columnas para descubrir qué casillas se pintan. Toca para rellenar y marca con X las que van vacías.',
	'penalty-flick'      => 'Desliza hacia la portería para chutar; curva el gesto para dar efecto. Engaña al portero y marca todos los penaltis que puedas.',
	'ping-pong-reflex'   => 'Mueve la pala para devolver la bola. Partidas a 11 puntos con 2 de diferencia y saque alterno.',
	'pixel-picross-xl'   => 'Deduce con las pistas numéricas qué casillas se rellenan para revelar el dibujo oculto. Tableros grandes para expertos.',
	'planet-hopper'      => 'Toca para saltar de un planeta al siguiente aprovechando su gravedad. No te pierdas en el espacio.',
	'pool-break'         => 'Arrastra para apuntar con la bola fantasma y elige la fuerza. Mete tus bolas y termina con la negra.',
	'putt-island'        => 'Arrastra para apuntar y medir la fuerza del golpe. Llega al hoyo evitando el agua y los búnkeres.',
	'reflex-grid'        => 'Toca las casillas que se iluminan lo más rápido posible. Cada acierto acelera el ritmo; un fallo resta tiempo.',
	'reversi'            => 'Coloca una ficha que encierre fichas rivales en línea para darles la vuelta. Gana quien tenga más fichas al final.',
	'rhythm-tap'         => 'Toca cada carril cuando la nota llegue a la línea. Los aciertos perfectos multiplican la puntuación.',
	'serpent-grid'       => 'Desliza o usa las flechas para girar la serpiente. Come para crecer y no choques contra ti mismo.',
	'sokoban-warehouse'  => 'Mueve al operario con las flechas o deslizando y empuja las cajas hasta las marcas. No puedes tirar de ellas.',
	'stack-tower-3d'     => 'Toca para soltar cada bloque sobre la torre. Lo que sobresale se corta; los encajes perfectos mantienen el tamaño.',
	'tangram-studio'     => 'Arrastra las piezas y tócalas para girarlas. Rellena la silueta completa sin dejar huecos.',
	'tower-guard'        => 'Construye y mejora torres junto al camino. Aguanta todas las oleadas sin perder las vidas de tu base.',
	'rock-belt'          => 'Gira y acelera la nave, dispara a los asteroides y esquiva los fragmentos.',
	'tetra-drop'         => 'Arrastra para mover la pieza, toca para girarla y desliza rápido hacia abajo para soltarla (arriba la guarda en reserva). Completa líneas para sumar puntos.',
	'tetra-drop-marathon'=> 'Maratón: empiezas en nivel 5 y la meta son 150 líneas. Arrastra para mover, toca para girar y desliza abajo para soltar la pieza.',
);
