"""Oleada 1 — agente «accion»: modos nuevos de topdown.js (bounce, coop) y platformer.js (race)."""

GAMES = [
    dict(
        title='Tanques Rebote',
        genre='arcade', tags=['tanques', 'rebote', 'arena', 'rondas', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='topdown',
        cfg=dict(mode='bounce', hud='bl', help='Mueve el tanque con la cruceta y dispara con A. Mantén B para quedarte quieto y girar solo la torreta: verás la trayectoria con sus rebotes. Cada bala rebota tres veces y, tras el primer rebote, también te alcanza a ti. Un impacto y fuera; gana quien llegue a 4 rondas.'),
        pad=dict(d='8', a='Fuego', b='Apuntar'),
        mp=(1, 4),
        desc=[
            'Tanques Rebote es un duelo de tanquetas de juguete en una arena de chapa donde cada disparo es una carambola. Las balas son bolas de energía del color de su dueño que rebotan hasta tres veces en paredes y bloques antes de apagarse, así que el mejor tiro casi nunca es el directo: se apunta a la esquina, se calcula el ángulo y se espera a que el rival salga de su escondite justo donde llega el segundo rebote.',
            'La regla que lo cambia todo: después de su primer rebote, tu propia bala también te puede alcanzar. Un impacto basta para quedarte fuera de la ronda, de modo que disparar a lo loco en un pasillo estrecho suele acabar en autogol. Solo puedes tener dos balas en juego a la vez y dos balas que chocan se anulan, lo que permite defenderse disparando contra la que viene. A partir de los 22 segundos la zona segura empieza a cerrarse para que nadie gane escondido.',
            'Con la cruceta mueves el tanque y la torreta mira hacia donde avanzas; si mantienes B te quedas clavado y la cruceta solo gira el cañón, con una línea de puntos que dibuja la trayectoria y marca con un aro al tanque que alcanzarías. En el móvil se usa el mando virtual del portal; con teclado, flechas, espacio para disparar y X para apuntar. En la tele juegan hasta cuatro personas con el móvil como mando y la CPU ocupa las plazas libres.',
            'Los obstáculos se generan en un cuarto de la arena y se reflejan en los otros tres, así ninguna esquina sale con ventaja. La CPU prueba ángulos, simula los rebotes y esquiva lo que ve venir, y se vuelve más fina cada vez que le ganas una partida. Las rondas duran menos de un minuto, el podio llega a las cuatro victorias y siempre apetece la revancha.',
        ],
        tips=['Mantén B antes de disparar: la línea de puntos te enseña los rebotes y si el tiro acaba volviendo hacia ti.',
              'No dispares pegado a una pared en diagonal: la bala vuelve enseguida y ya puede darte.',
              'Si una bala viene directa, dispara contra ella: dos balas que chocan desaparecen.'],
        players='1–4 jugadores',
    ),
    dict(
        title='Mazmorra a Cuatro',
        genre='arcade', tags=['mazmorra', 'cooperativo', 'clases', 'jefes', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='topdown',
        cfg=dict(mode='coop', hud='bl', help='Elige clase (← →) y pulsa A para estar listo. Te mueves con la cruceta y atacas solo al enemigo más cercano; A lanza la habilidad de tu clase y B hace una voltereta. Si un compañero cae, quédate a su lado para levantarlo. Limpiad la sala, salid por la puerta y elegid una mejora para todo el equipo.'),
        pad=dict(d='8', a='Habilidad', b='Rodar'),
        mp=(1, 4),
        desc=[
            'Mazmorra a Cuatro es una incursión cooperativa por salas de piedra iluminadas con antorchas en la que el equipo entero gana o cae junto. Antes de entrar cada jugador elige clase: el Caballero aguanta seis golpes y barre a su alrededor con el Torbellino, la Arquera dispara rápido y suelta una lluvia de doce flechas, la Maga lanza orbes que atraviesan enemigos y congela a los que tiene cerca, y el Clérigo reparte mazazos y con su Plegaria cura y pone en pie a los compañeros caídos.',
            'Los ataques básicos salen solos contra el enemigo más próximo, así que la partida va de colocarse bien, esquivar y usar la habilidad en el momento justo. Quien se queda sin corazones no muere: queda tendido pidiendo ayuda y cualquier compañero que se quede a su lado unos segundos lo levanta con media vida. Si todos caen a la vez, la expedición termina. Las monedas suman al marcador del equipo y cada corazón cura a quien lo recoge.',
            'Cada quinta sala espera un jefe con barra de vida propia: un ojo que dispara en abanico o un caballero esqueleto que avisa antes de embestir. Al vaciar la sala se abre la puerta de la derecha y el grupo elige una mejora común, como más cadencia, más daño, más vida para todos o habilidades que se recargan antes. Cuantos más héroes hay, más enemigos salen y más resistentes son, así que la dificultad se ajusta sola.',
            'Se juega con la cruceta, A para la habilidad y B para rodar, en el mando virtual del portal, con teclado o con mando físico. Si juegas en solitario te acompaña un aliado controlado por la CPU que te sigue, pelea según su clase y corre a levantarte si caes; en la tele pueden entrar hasta cuatro jugadores con el móvil como mando, incluso a mitad de partida.',
        ],
        tips=['Combinad clases: el Caballero delante atrae a los enemigos mientras la Arquera y la Maga disparan desde atrás.',
              'La Plegaria del Clérigo levanta al instante a todos los caídos que estén cerca: guárdala para las salas de jefe.',
              'La voltereta con B te hace invulnerable un instante; úsala cuando el jefe esqueleto se ponga rojo.'],
        players='1–4 jugadores (cooperativo)',
    ),
    dict(
        title='Carrera de Plataformas',
        genre='platformer', tags=['carrera', 'plataformas', 'rondas', 'versus', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='platformer',
        cfg=dict(mode='race', hud='bl', theme='meadow', spikes=0.15, enemies=0.3, help='Corre con ← → y salta con A (mantén para saltar más alto); B da un empujón. La cámara sigue al primero: si te quedas fuera por la izquierda, caes a un foso o tocas pinchos o enemigos, pierdes la ronda. Pisa la cabeza de un rival para aturdirlo. Gana la ronda quien toque la bandera o el último en pie; a 3 rondas.'),
        pad=dict(d='h', a='Saltar', b='Empujón'),
        mp=(1, 4),
        desc=[
            'Carrera de Plataformas junta a cuatro corredores en el mismo nivel y en la misma pantalla. No hay pantalla partida ni fantasmas: la cámara sigue a quien va en cabeza y el borde izquierdo es una línea roja que elimina a cualquiera que se quede atrás. Gana la ronda el primero que toca la bandera de meta o el último que sigue en pie, y quien llega a tres rondas sube a lo más alto del podio.',
            'Los niveles se generan en cada ronda con fosos, escalones, pasarelas de madera, pinchos y enemigos que se pueden pisar, y cambian de ambiente entre pradera, selva, atardecer, nieve, castillo y cielo. La carrera arranca tranquila y la cámara acelera poco a poco, así que los primeros segundos sirven para coger ritmo y los últimos son un sprint. Quien va ganando sale desde atrás en la ronda siguiente, lo que mantiene la emoción hasta el final.',
            'Además de correr y saltar hay contacto: caer sobre la cabeza de un rival lo deja aturdido un momento y el empujón con B lo lanza hacia atrás o hacia el borde de un foso. Se controla con la cruceta horizontal, A para saltar y B para empujar, desde el mando virtual del portal, con teclado (flechas, espacio y X) o con mando físico; en la tele cada jugador usa su móvil y la CPU rellena las plazas vacías.',
            'Los corredores de la CPU leen el terreno que tienen delante para saltar fosos y escalones a tiempo, pisan enemigos y de vez en cuando se equivocan; cada victoria tuya los hace un poco más rápidos y precisos, así que el reto crece contigo. Cada ronda dura menos de medio minuto: ideal para echar unas cuantas seguidas en el sofá.',
        ],
        tips=['No hace falta ir primero todo el rato: ir segundo te deja ver el terreno y aprovechar los errores del líder.',
              'Guarda el empujón para cuando un rival esté al borde de un foso.',
              'Mantén A pulsado en los escalones altos; un toque corto sirve para los fosos estrechos.'],
        players='1–4 jugadores',
    ),
]
