"""Oleada 1 — agente «equipos»: petardos en rejilla (bomber) y deportes de equipo (teamball)."""

GAMES = [
    dict(
        title='Petardo Plaza', genre='party', tags=['petardos', 'laberinto', 'versus', 'fiesta', 'vector'],
        orient='auto', aspect='4:3', inputs='TKG', engine='bomber', players='1–4 jugadores',
        cfg=dict(hud='bl', help='Muévete con el joystick o las flechas y suelta un petardo con A. La traca estalla en cruz, rompe las cajas y deja mejoras: alcance, más petardos, zapatillas y patada. Gana la ronda quien quede en pie; el primero en ganar 2 rondas se lleva la plaza.',
                 rules=dict(fuse=2.4, range=2, bombs=1, speed=3.3, round=60, wins=2)),
        pad=dict(d='8', a='Petardo'), mp=(1, 4),
        desc=[
            'Petardo Plaza convierte la plaza del pueblo en fiesta mayor: cuatro vecinos con gorro de verbena arrancan en las esquinas, rodeados de cajas de fruta y bolardos de piedra, y solo uno puede terminar la ronda en pie. Cada petardo que sueltas chisporrotea unos segundos y revienta en una traca en forma de cruz que recorre las calles hasta chocar con la piedra.',
            'Las cajas saltan por los aires y a veces esconden mejoras: pólvora para alargar la explosión, petardos extra para soltar varios a la vez, zapatillas para correr más y la bota, que te deja empujar de una patada un petardo encendido hasta el otro extremo de la calle. Las explosiones se encadenan, así que un solo petardo bien puesto puede prender media plaza. Cuando el reloj llega a cero empieza la muerte súbita y la plaza se va cerrando desde fuera hacia dentro.',
            'Se juega con el joystick y un único botón: en el móvil, con el mando virtual; en el ordenador, con las flechas y Espacio; en la tele, hasta cuatro personas con su propio móvil como mando. Las plazas vacías las ocupa la CPU, que lee el mapa de peligro para esquivar la traca, persigue al rival más cercano y aprende: cada vez que le ganas, juega un poco mejor.',
            'Engancha porque cada ronda dura menos de un minuto y siempre parece que la siguiente es la buena: encerrar a un amigo entre dos petardos o salvarte por una casilla da para comentarlo durante toda la revancha.',
        ],
        tips=['Antes de soltar un petardo mira por dónde vas a escapar: un callejón sin salida es una trampa para ti mismo.',
              'La bota sirve para atacar desde lejos: coloca el petardo y empújalo hacia el rival que se esconde detrás de una esquina.',
              'En la muerte súbita busca el centro de la plaza pronto; los bordes son los primeros en cerrarse.'],
    ),
    dict(
        title='Fútbol de Plaza', genre='sports-casual', tags=['futbol', 'equipos', 'versus', 'vector'],
        orient='auto', aspect='fill', inputs='TKG', engine='teamball', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='futbol', time=120, help='Mueve a tu jugador con el joystick o las flechas. Con balón, A pasa al compañero y B mantenido carga el tiro; sin balón, A pide el pase o cambia al jugador más cercano y B hace una entrada. Dos minutos de partido; si hay empate, gol de oro.'),
        pad=dict(d='8', a='Pase', b='Tiro'), mp=(1, 4),
        desc=[
            'Fútbol de Plaza es el partido de siempre en la plaza del barrio, pero con porterías de verdad y un árbitro que no se cansa: dos contra dos en un campo de césped visto desde arriba, con vallas que devuelven el balón y dos minutos de reloj para decidir quién presume hasta mañana. El balón rueda con su propio peso, bota en las esquinas y se queda pegado al pie de quien lo conduce.',
            'Con el balón, A lo toca al compañero y B, mantenido, carga un disparo que busca el palo; cuanto más esperas, más fuerte sale, pero más tiempo te dejan para robártela. Sin balón, A pide el pase o salta al compañero más cercano a la pelota y B se lanza en plancha para quitarla. Si al final del tiempo el marcador sigue igualado, llega la prórroga de gol de oro: el primero que marca, gana.',
            'En el móvil juegas con el joystick virtual y dos botones; en el ordenador, flechas, Espacio y X; en la tele, hasta cuatro amigos con su propio móvil como mando, rojos contra azules. Cualquier hueco lo cubre la CPU, que se desmarca, cubre la portería y aprende de tus goles.',
        ],
        tips=['Un pase rápido al compañero desmarcado vale más que regatear a los dos rivales.',
              'No cargues el tiro a lo loco: con medio segundo basta si estás cerca del área.',
              'La entrada deja al que la hace en el suelo un instante; úsala solo cuando el rival va solo.'],
    ),
    dict(
        title='Hockey de Barrio', genre='sports-casual', tags=['hockey', 'patines', 'equipos', 'versus', 'vector'],
        orient='auto', aspect='fill', inputs='TKG', engine='teamball', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='hockey', time=120, help='Patina con el joystick o las flechas: vas con inercia, así que frena con antelación. Con el disco, A pasa y B mantenido carga el latigazo; sin disco, A cambia al jugador más cercano y B empuja para robar. Dos minutos; si hay empate, gol de oro.'),
        pad=dict(d='8', a='Pase', b='Tiro'), mp=(1, 4),
        desc=[
            'Hockey de Barrio saca los patines a la pista de la esquina: dos contra dos sobre un suelo pulido, un disco que vuela a ras de suelo y unas vallas que lo devuelven con más mala idea que el mejor defensa. Nadie frena en seco; cada giro se patina y cada choque se nota, así que el partido va siempre un poco más deprisa de lo que te gustaría.',
            'El disco se queda en la pala de quien lo controla. A lo pasa al compañero y B, mantenido, arma un latigazo que sale disparado hacia la portería; los rebotes en las vallas son parte del juego y un tiro cruzado contra la banda puede acabar dentro. Sin el disco, B empuja al rival para robárselo y A te cambia al jugador más cercano. Empate al final de los dos minutos: gol de oro.',
            'Se juega con joystick y dos botones en el móvil, con flechas, Espacio y X en el teclado y, en la tele, con hasta cuatro móviles a la vez. La CPU rellena las plazas vacías, patina con la misma inercia que tú y se vuelve más fina cuanto más le ganas.',
        ],
        tips=['Empieza a frenar antes de llegar: el patín sigue deslizando medio campo.',
              'Tira contra la valla cuando el portero tape el hueco; el rebote suele entrar por el otro lado.'],
    ),
    dict(
        title='Coches con Balón', genre='sports-casual', tags=['coches', 'futbol', 'equipos', 'versus', 'vector'],
        orient='auto', aspect='fill', inputs='TKG', engine='teamball', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='coches', time=120, help='Apunta con el joystick o las flechas y el coche gira hacia allí. A salta para golpear el balón por arriba y B es el turbo (se recarga solo). Empuja el balón gigante hasta la portería rival. Dos minutos; si hay empate, gol de oro.'),
        pad=dict(d='8', a='Saltar', b='Turbo'), mp=(1, 4),
        desc=[
            'Coches con Balón mezcla un partido de fútbol con una tarde de coches de choque: cuatro bólidos pequeños y rabiosos en una arena de neón y, en medio, un balón que es casi tan grande como ellos. No hay manos ni pies; todo se decide con el morro del coche, los saltos y un turbo que se agota justo cuando más falta hace.',
            'El volante es el joystick: señala hacia dónde quieres ir y el coche gira hasta encarar esa dirección. A pega un salto que permite tocar el balón cuando bota alto, y B enciende el turbo para llegar primero o para pegar un empujón a un rival. El balón tiene peso y altura propia: si lo golpeas en el aire puede pasar por encima de todos o chocar con el larguero.',
            'En el móvil, joystick y dos botones; con teclado, flechas, Espacio y X; en la tele, hasta cuatro jugadores con el móvil. Las plazas vacías las ocupan coches de la CPU que atacan, defienden y mejoran partido a partido. Lo que engancha es la física: ningún gol sale igual y los rebotes locos se celebran como una final.',
        ],
        tips=['Guarda un poco de turbo para volver a defender; un contraataque sin nadie atrás es gol casi seguro.',
              'Llega al balón desde detrás, alineado con la portería rival, y empuja en lugar de chocar de lado.'],
    ),
    dict(
        title='Vóley Playa', genre='sports-casual', tags=['voley', 'playa', 'equipos', 'versus', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG', engine='teamball', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='voley', help='Muévete a los lados con el joystick o las flechas; el toque es automático al llegar al balón. A salta: junto a la red, el toque en el aire es un remate. B pasa el balón directo al otro campo. Máximo tres toques por equipo. Partido a 7 puntos con 2 de diferencia.', pts=7),
        pad=dict(d='h', a='Saltar', b='Pasar'), mp=(1, 4),
        desc=[
            'Vóley Playa se juega de lado, con la arena caliente, el mar al fondo y una red que separa a dos parejas decididas a no dejar caer el balón. Recibir, colocar y rematar: tres toques como máximo por equipo y un cuarto que es falta. Los puntos se ganan como en la playa de verdad, con saques, carreras desesperadas y algún remate que deja marca en la arena.',
            'Te mueves a izquierda y derecha y el toque sale solo cuando llegas debajo del balón, así que lo importante es leer dónde cae. A salta; si estás pegado a la red y tocas en el aire, el golpe se convierte en un remate hacia abajo. B manda el balón directo al campo contrario cuando no quieres arriesgar. Quien gana el punto saca; el partido se juega a 7 con dos de diferencia.',
            'En el móvil basta con el joystick horizontal y dos botones; en el teclado, flechas, Espacio y X; en la tele, hasta cuatro amigos por parejas. Si falta alguien, la CPU coloca y remata por ti y va afinando con cada derrota. Engancha porque cada punto dura segundos, un partido entero cabe en tres minutos y siempre hay una jugada que repetir.',
        ],
        tips=['Deja que tu compañero reciba y coloca el segundo toque cerca de la red para rematar en el tercero.',
              'Contra un remate, retrocede un paso: el balón baja rápido y lejos.'],
    ),
    dict(
        title='Balón Prisionero', genre='sports-casual', tags=['balon-prisionero', 'esquivar', 'equipos', 'versus', 'vector'],
        orient='auto', aspect='fill', inputs='TKG', engine='teamball', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='prisionero', round=60, wins=2, help='Muévete por tu mitad del campo con el joystick o las flechas. Recoge un balón y lánzalo con A: el tiro busca al rival más cercano. Pulsa B justo cuando te llegue un balón para atraparlo. Si te dan, vas a la cárcel tras el campo rival; desde allí, si eliminas a alguien, vuelves. Gana 2 rondas.'),
        pad=dict(d='8', a='Lanzar', b='Atrapar'), mp=(1, 4),
        desc=[
            'Balón Prisionero trae al móvil el juego del patio del colegio: dos equipos de tres, una raya en medio, tres balones sobre la pista y la cárcel esperando detrás de cada campo. Si te dan, te vas a la cárcel; si desde allí alcanzas a un rival, vuelves a tu campo. La ronda termina cuando uno de los equipos se queda sin nadie en pie.',
            'Corres por tu mitad sin pisar la raya, recoges un balón y lo lanzas con A hacia el rival más a tiro. El momento clave es B: si lo pulsas justo cuando un balón está a punto de darte, lo atrapas y el lanzador acaba en la cárcel. Hay que decidir en cada instante entre esquivar, atrapar o atacar. Gana el primer equipo en llevarse dos rondas, y si el reloj se agota con los mismos jugadores en pie, se decide a bola de oro.',
            'En el móvil se juega con joystick y dos botones; con teclado, flechas, Espacio y X; y en la tele, hasta cuatro amigos, cada uno con su móvil. Los huecos los llena la CPU, que esquiva, se arriesga y atrapa mejor cuanto más la derrotas.',
        ],
        tips=['No te quedes pegado a la raya: tienes menos tiempo para reaccionar.',
              'Atrapar vale el doble que esquivar: salvas tu plaza y mandas al lanzador a la cárcel.',
              'Desde la cárcel apunta a los rivales que están de espaldas mirando a tu equipo.'],
    ),
    dict(
        title='Fútbol Cabezón', genre='sports-casual', tags=['futbol', 'cabezones', 'versus', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG', engine='teamball', players='1–2 jugadores',
        cfg=dict(hud='bl', mode='cabezon', time=90, help='Muévete a los lados con el joystick o las flechas. A salta para cabecear y B chuta; si chutas en el aire con el balón encima, sale una chilena. Llena la barra con toques y goles para lanzar un superdisparo de fuego. Noventa segundos; si hay empate, gol de oro.'),
        pad=dict(d='h', a='Saltar', b='Chutar'), mp=(1, 2),
        desc=[
            'Fútbol Cabezón es un duelo uno contra uno en un estadio visto de lado, con dos futbolistas de cabeza enorme y cuerpo diminuto que se juegan la gloria en noventa segundos. El balón bota, rueda por el larguero y se queda colgando en el aire el tiempo justo para que alguien salte a por él.',
            'Te mueves a izquierda y derecha, saltas con A para cabecear y chutas con B. Si chutas en pleno salto con el balón por encima, el remate sale de chilena. Cada toque y cada gol llenan la barra de energía y, cuando está llena, el siguiente chut se convierte en un superdisparo de fuego que deja aturdido al rival si intenta pararlo. Si el reloj llega a cero con empate, gol de oro.',
            'En el móvil, joystick horizontal y dos botones; en el teclado, flechas, Espacio y X; en la tele, dos amigos cara a cara con su móvil. Solo, te enfrentas a la CPU, que salta, despeja y chuta cada vez mejor según vas ganando. Engancha por lo absurdo: partidos cortos, goles imposibles y revancha inmediata.',
        ],
        tips=['Quédate un poco por detrás del balón; así lo cabeceas hacia delante y no hacia tu portería.',
              'Guarda el superdisparo para cuando el rival esté lejos de su portería.'],
    ),
]
