"""Oleada 1 — agente «letras»: preguntas y palabras (motores trivia y palabras). Datos propios en games/_data/."""

GAMES = [
    dict(
        title='Trivia de Sobremesa',
        genre='trivia',
        tags=['preguntas', 'cultura-general', 'concurso', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG',
        engine='trivia',
        cfg=dict(mode='quiz', help='Diez preguntas de seis categorías. Toca la respuesta (o elige con las flechas y pulsa Espacio). En la tele: joystick para elegir A, B, C o D y A para pulsar. Acertar rápido suma más y la última vale doble.'),
        pad=dict(d='8', a='Responder'),
        mp=(1, 4),
        desc=[
            'Trivia de Sobremesa es el concurso de preguntas para jugar después de comer, con la familia en el sofá o tú solo contra tres rivales de la casa. Cada ronda tiene diez preguntas y una ruleta decide la categoría: Geografía, Historia, Ciencia y naturaleza, Deporte y juegos, Arte y cultura o Lengua y cocina. Hay más de ochocientas preguntas escritas para el juego, ordenadas por dificultad, y la ronda arranca con las fáciles para calentar y termina con las que hacen dudar a cualquiera.',
            'En el móvil basta con tocar la respuesta; con teclado eliges con las flechas y confirmas con Espacio. En la tele cada jugador usa su móvil como pulsador: el joystick mueve la selección entre A, B, C y D y el botón A la bloquea. Si la conexión lo permite, las opciones llegan también a la pantalla del móvil para responder sin que nadie vea lo que eliges. Las plazas vacías las ocupa la CPU, que acierta más o menos según la dificultad y se vuelve más lista cada vez que le ganas.',
            'La gracia está en la rapidez: acertar da 100 puntos y hasta 100 más según lo pronto que respondas, tres aciertos seguidos suman un extra y la última pregunta vale doble, así que nadie está descartado hasta el final. Al acabar, podio con confeti y otra ronda con preguntas que todavía no has visto.',
        ],
        tips=[
            'Si dudas, descarta primero las opciones imposibles: responder rápido entre dos suele compensar.',
            'La última pregunta vale doble; guarda la calma aunque vayas por detrás.',
            'Tres aciertos seguidos dan puntos extra: la racha pesa más de lo que parece.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Verdad o Bulo',
        genre='trivia',
        tags=['preguntas', 'verdadero-falso', 'curiosidades', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG',
        engine='trivia',
        cfg=dict(mode='tf', help='Lee la afirmación y decide si es verdad o un bulo. Toca tu respuesta (o ← Verdad, → Bulo y Espacio). En la tele: joystick a un lado y A. Acertar rápido suma más; fallar resta 50. Tras cada una verás la explicación.'),
        pad=dict(d='h', a='Responder'),
        mp=(1, 4),
        desc=[
            'Verdad o Bulo pone a prueba lo que creemos saber. Cada afirmación aparece en una tarjeta y tienes unos segundos para decidir si es cierta o si es uno de esos bulos que se repiten sin que nadie los compruebe: que los peces de colores olvidan todo en tres segundos, que la Gran Muralla se ve desde la Luna o que los murciélagos son ciegos. Después de responder, la tarjeta se da la vuelta y explica en una frase por qué es verdad o por qué no.',
            'Solo hay dos botones, así que se aprende en un momento. En el móvil tocas Verdad o Bulo; con teclado usas la flecha izquierda o derecha y confirmas con Espacio. En la tele, cada jugador empuja el joystick de su móvil hacia un lado y pulsa A. Pueden jugar hasta cuatro personas y la CPU rellena los huecos, con un nivel que sube cuando la vencéis.',
            'Hay más de doscientas setenta afirmaciones propias sobre animales, ciencia, historia, geografía y costumbres, mezcladas para que cada ronda de diez sea distinta. Acertar suma entre 100 y 200 puntos según tu rapidez, pero fallar resta 50: contestar a lo loco no sale a cuenta. Engancha porque siempre aprendes algo y porque discutir la respuesta con quien tienes al lado forma parte del juego.',
        ],
        tips=[
            'Desconfía de las frases con «siempre» o «nunca»: muchos bulos exageran.',
            'Fallar resta 50: si no tienes ni idea, esperar no quita puntos.',
            'Lee la explicación: las mismas ideas vuelven en otras afirmaciones.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Palabra del Día',
        genre='trivia',
        tags=['palabras', 'diario', 'logica', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG',
        engine='palabras',
        cfg=dict(mode='daily', help='Adivina la palabra de cinco letras en seis intentos. Escribe con el teclado de la pantalla o el del ordenador y pulsa ENVIAR. Verde: letra en su sitio; amarillo: está en otra posición; gris: no está. Con mando: flechas para moverte por el teclado, A escribe y B borra.'),
        pad=dict(d='8', a='Pulsar', b='Borrar', t=1),
        mp=None,
        desc=[
            'Palabra del Día es un reto corto para empezar la mañana o para la pausa del café: una palabra española de cinco letras, seis intentos y la misma solución para todos los jugadores durante el día. No hace falta registrarse ni conexión especial; la palabra se calcula a partir de la fecha, así que puedes comparar tu resultado con amigos y familia sabiendo que todos os enfrentáis al mismo desafío.',
            'Escribe una palabra válida y pulsa ENVIAR. Cada letra se da la vuelta y cambia de color: verde si está en su sitio, amarillo si aparece en otra posición y gris si no forma parte de la solución. El teclado de la pantalla incluye la Ñ y se colorea con las pistas que vas descubriendo. Las tildes no cuentan, así que basta con escribir las letras. En el ordenador puedes usar el teclado físico, y con mando te mueves por las teclas con las flechas, escribes con A y borras con B.',
            'Al terminar verás tus estadísticas —partidas, porcentaje de victorias, racha actual y mejor racha— y un gráfico con el número de intentos que sueles necesitar. El botón Compartir copia tu resultado en cuadrados de colores, sin desvelar la palabra, y si te quedas con ganas puedes seguir en modo práctica con palabras al azar que no cuentan para la racha.',
        ],
        tips=[
            'Empieza con palabras con varias vocales distintas, como AUDIO o PIANO, para descubrir mucho de golpe.',
            'Una letra amarilla no puede volver a la misma casilla: muévela.',
            'Recuerda que las letras pueden repetirse: si te atascas, prueba con una doble.',
        ],
        players='1 jugador',
    ),
    dict(
        title='Ahorcado Ilustrado',
        genre='trivia',
        tags=['palabras', 'ahorcado', 'turnos', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG',
        engine='palabras',
        cfg=dict(mode='hang', help='Adivina la palabra de la categoría letra a letra antes de que se complete el dibujo (8 fallos). Toca una letra o escríbela. En la tele: joystick para elegir letra y A. Acertar suma 10 por letra y repites turno; completar la palabra, +30.'),
        pad=dict(d='8', a='Elegir'),
        mp=(1, 4),
        desc=[
            'Ahorcado Ilustrado recupera el juego de papel y lápiz de toda la vida con un dibujo animado propio: un prado soleado, una horca de madera que se va levantando pieza a pieza y un personaje de trazo grueso que aparece por partes cada vez que alguien falla. Si la palabra se completa a tiempo, el muñeco salta libre y saluda; si se llega a ocho fallos, se acabó y toca descubrir la solución.',
            'Cada partida tiene cinco palabras y siempre sabes la categoría: animales, frutas y verduras, oficios, instrumentos, ciudades de España, cosas de la cocina y muchas más, con más de setecientas palabras escritas para el juego. Se juega por turnos: si aciertas una letra sumas 10 puntos por cada vez que aparece y vuelves a elegir; si fallas, el dibujo avanza y pasa el turno. Quien completa la palabra se lleva 30 puntos extra.',
            'En el móvil tocas las letras del alfabeto de la pantalla, Ñ incluida, y en el ordenador puedes escribirlas directamente. En la tele pueden jugar hasta cuatro personas con el móvil como mando: el joystick mueve la selección y A elige. Si juegas solo, te enfrentas a una CPU que razona con las letras que ya se han dicho y que mejora cada vez que le ganas. Al final, podio y revancha.',
        ],
        tips=[
            'Empieza por las vocales y por letras frecuentes como S, R o N.',
            'Fíjate en la categoría y en la longitud: descartan muchas palabras.',
            'Acertar te deja repetir turno; arriesgar con una letra rara puede regalar el turno al rival.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Sopa de Letras',
        genre='trivia',
        tags=['palabras', 'sopa-de-letras', 'relajante', 'vector'],
        orient='auto', aspect='fill', inputs='TKM',
        engine='palabras',
        cfg=dict(mode='sopa', help='Encuentra las 8 palabras de la categoría: arrastra el dedo o el ratón desde la primera letra hasta la última. Con teclado: flechas para moverte, Espacio marca el inicio y Espacio de nuevo el final. Cuanto más rápido, más puntos.'),
        pad=None,
        mp=None,
        desc=[
            'Sopa de Letras es el pasatiempo de siempre en versión táctil: una hoja de papel llena de letras, ocho palabras escondidas de una misma categoría y todo el tiempo del mundo para encontrarlas, aunque el reloj premia a quien va rápido. Cada sopa se genera en el momento, así que nunca se repite, y las palabras salen de listas propias: animales, países, deportes, ropa, partes del cuerpo, fiestas, cosas del mar y muchas más.',
            'Para marcar una palabra, arrastra el dedo desde su primera letra hasta la última; la selección se ajusta sola a la línea recta más cercana, en horizontal, vertical o diagonal. Si aciertas, la palabra queda rodeada con un color y se tacha de la lista. Con ratón funciona igual, y con teclado mueves un cursor con las flechas y marcas inicio y final con Espacio. Si pasas un rato sin encontrar nada, la primera letra de una palabra pendiente parpadea como pista.',
            'La dificultad crece contigo: al principio las palabras solo van de izquierda a derecha y de arriba abajo; al completar sopas se añaden las diagonales, después las palabras al revés y por último todas las direcciones. Es un juego tranquilo, ideal para desconectar unos minutos, y a la vez engancha intentar bajar tu mejor tiempo.',
        ],
        tips=[
            'Busca letras poco comunes de la lista, como Ñ, Z o J: se localizan antes.',
            'Recorre la rejilla fila a fila buscando la primera letra de la palabra más larga.',
            'Desde el nivel 3 hay palabras al revés: lee también de derecha a izquierda.',
        ],
        players='1 jugador',
    ),
]
