"""Oleada 2 — agente «batalla»: motores nuevos artillery.js (cannon, worms, snow) y dogfight.js;
modos nuevos shooter.js (coop) y rocks.js (arena)."""

GAMES = [
    dict(
        title='Cañones de Colina',
        genre='strategy-cards', tags=['artilleria', 'turnos', 'viento', 'tanques', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='artillery',
        cfg=dict(mode='cannon', hud='bl', help='Por turnos. ↑ ↓ suben y bajan el cañón, ← → mueven el tanque mientras quede gasolina. Mantén A para cargar la fuerza y suelta para disparar; B cambia de munición. Mira la manga de viento antes de tirar. En el móvil también puedes arrastrar hacia atrás desde cualquier punto, como un tirachinas, y soltar. Gana la ronda el último tanque en pie; el primero que gane 2 rondas se lleva la partida.'),
        pad=dict(d='8', a='Disparo', b='Arma'),
        mp=(1, 4),
        desc=[
            'Cañones de Colina es un duelo de artillería por turnos sobre unas lomas verdes que cada disparo va dejando llenas de cráteres. Cada jugador maneja un tanquecito de juguete con su color, y en su turno ajusta el ángulo del cañón, carga la fuerza y suelta el obús. El terreno es completamente destructible: una explosión abre un hoyo, deja al rival sin suelo bajo las orugas o le obliga a disparar desde el fondo de un agujero.',
            'El viento cambia en cada turno y la manga del marcador indica hacia dónde sopla y con qué fuerza, así que un tiro que ayer entraba limpio hoy se queda corto. Cada tanque lleva munición ilimitada de obús normal, dos disparos triples que se abren en abanico y un obús pesado que hace un cráter enorme. También puedes moverte un poco mientras dure la gasolina para salir de una hondonada o ponerte a cubierto detrás de una colina. Si el agua del fondo empieza a subir, más vale buscar terreno alto.',
            'Juegan de dos a cuatro tanques y la CPU rellena las plazas libres: en los primeros turnos falla bastante y, cuantas más partidas le ganas, más fina se vuelve su puntería. En la tele cada jugador usa su móvil como mando; en el ordenador bastan las flechas, espacio para disparar y X para cambiar de arma, y en el móvil se puede apuntar arrastrando el dedo como si fuera un tirachinas. Gana la partida el primero que se lleve dos rondas.',
        ],
        tips=['Tras un fallo, corrige solo una cosa (ángulo o fuerza): así aprendes enseguida cuánto mueve cada ajuste.',
              'Con viento fuerte en contra, sube el ángulo y carga más: el obús pesado es el que menos se desvía.',
              'Dispara al suelo bajo el rival: si cae por el hueco también pierde vida y puede acabar en el agua.'],
        players='1–4 jugadores',
    ),
    dict(
        title='Bichos Artilleros',
        genre='strategy-cards', tags=['artilleria', 'equipos', 'turnos', 'bichos', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='artillery',
        cfg=dict(mode='worms', hud='bl', help='Cada equipo tiene 3 bichos y juega un bicho por turno. ← → caminan (suben pequeños desniveles), ↑ ↓ apuntan, mantén A para cargar y suelta para lanzar; B cambia de arma: bazuca (le afecta el viento), granada (rebota y estalla a los 3 s) y cuerda (A la lanza, ↑ ↓ la acortan o alargan, ← → balancean, A o B te sueltan). Cuidado con el agua. Gana el último equipo con bichos vivos.'),
        pad=dict(d='8', a='Disparo', b='Arma'),
        mp=(1, 4),
        desc=[
            'Bichos Artilleros es una batalla de equipos por turnos en una isla de jungla llena de salientes, túneles y plataformas flotantes. Cada jugador dirige a tres bichos cabezones de su color y, en su turno, mueve a uno solo: puede caminar, trepar pequeños escalones, apuntar y lanzar algo explosivo contra los bichos rivales antes de que se acabe el reloj. El terreno se deshace con cada explosión, así que la isla cambia de forma durante toda la partida.',
            'El arsenal es corto pero da mucho juego. La bazuca vuela recta y fuerte, aunque el viento la desvía; la granada ignora el viento, rebota por las pendientes y explota a los tres segundos, ideal para colarla en un agujero; y la cuerda ninja se engancha a cualquier pared o techo para balancearse, cruzar un barranco o escapar de una posición comprometida. Las explosiones empujan, así que a veces es mejor tirar a un bicho al agua que intentar quitarle toda la vida.',
            'Pueden jugar hasta cuatro equipos y la CPU controla los que falten. Al principio apunta con bastante error y camina poco, pero mejora cada vez que le ganas una partida, de modo que siempre hay reto. Tras unos cuantos turnos el nivel del mar empieza a subir y va tragándose la parte baja de la isla, lo que obliga a subir y acaba con las partidas eternas. Se juega en la tele con el móvil como mando, con teclado o con el mando virtual.',
        ],
        tips=['La granada rebota: úsala para alcanzar a bichos escondidos en un hueco donde la bazuca no llega.',
              'Una explosión cerca del borde vale más que un impacto directo: el empujón puede mandar al rival al agua.',
              'Usa la cuerda para subir a lo alto antes de que suba el agua; desde arriba se apunta mejor.'],
        players='1–4 equipos',
    ),
    dict(
        title='Guerra de Bolas de Nieve',
        genre='arcade', tags=['nieve', 'fuertes', 'tiempo-real', 'invierno', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='artillery',
        cfg=dict(mode='snow', hud='bl', help='En tiempo real. Mantén B para agacharte: te cubres y fabricas bolas (hasta 5). ← → te mueven, ↑ ↓ suben o bajan el brazo, mantén A para coger fuerza y suelta para lanzar. Cada bola que te da te quita un corazón y te deja aturdido un momento. En el móvil arrastra hacia atrás y suelta para lanzar. Tres rondas de 60 s; puntúa quien más aguanta.'),
        pad=dict(d='8', a='Lanzar', b='Agachar'),
        mp=(1, 4),
        desc=[
            'Guerra de Bolas de Nieve es una pelea invernal en tiempo real entre niños abrigados hasta las orejas, cada uno parapetado detrás de su propio fuerte de ladrillos de nieve. No hay turnos: todos amasan, apuntan y lanzan a la vez, y la puntería se mezcla con los reflejos para agacharse justo cuando llega la bola del vecino. Cada impacto quita un corazón y deja al niño aturdido un segundo, justo el tiempo que aprovechan los demás para rematar.',
            'Las bolas no salen de la nada: hay que agacharse detrás del muro para fabricarlas una a una, y mientras estás agachado también estás a cubierto. Lanzar sigue una parábola con algo de viento, así que conviene subir el brazo para pasar por encima del fuerte rival. Los muros se van desmoronando con los impactos y, a medida que avanza la ronda, el sol los derrite cada vez más deprisa, de modo que el final de cada asalto siempre es a campo abierto.',
            'Se juegan tres rondas de un minuto y en cada una se reparten tres, dos, uno y cero puntos según quién quede en pie y con más corazones. La CPU espera unos segundos antes de su primer lanzamiento, fabrica bolas, esquiva y afina la puntería cuando le ganas partidas. En la tele entran hasta cuatro jugadores con el móvil como mando; en solitario puedes jugar con teclado, mando o tocando la pantalla como un tirachinas.',
        ],
        tips=['Ten siempre dos o tres bolas de reserva: quedarte sin munición en campo abierto es lo peor que puede pasar.',
              'Lanza justo cuando el rival se levanta para tirar: sale de su cobertura y está quieto cargando.',
              'Al final de la ronda los fuertes casi no protegen; muévete para que no te encuentren parado.'],
        players='1–4 jugadores',
    ),
    dict(
        title='Duelo de Biplanos',
        genre='arcade', tags=['aviones', 'biplanos', 'combate-aereo', 'rondas', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='dogfight',
        cfg=dict(mode='duel', hud='bl', help='La cruceta indica hacia dónde quieres que apunte el morro: el avión gira hacia esa dirección. A dispara la ametralladora (se recalienta si no la sueltas) y B hace un rizo que esquiva casi todas las balas. Si subes demasiado despacio el avión entra en pérdida y cae de morro: baja para recuperar velocidad. Derriba a los demás; 3 rondas de 75 s.'),
        pad=dict(d='8', a='Fuego', b='Rizo'),
        mp=(1, 4),
        desc=[
            'Duelo de Biplanos es un combate aéreo de vista lateral entre avionetas de tela y madera que se persiguen sobre una granja, entre nubes y molinos. Cada jugador pilota un biplano de su color y dirige el morro con la cruceta: el avión gira hacia donde apuntas y el motor hace el resto. Al salir por un lado de la pantalla apareces por el otro, así que la persecución nunca termina contra una pared.',
            'El vuelo tiene su física. Si subes en vertical sin velocidad, el avión entra en pérdida, el motor tose y el morro cae hacia el suelo hasta que recupera sustentación; si picas demasiado cerca de la hierba, te estrellas. La ametralladora dispara ráfagas rápidas pero se recalienta si no sueltas el gatillo, y el rizo hace un giro completo que te quita de la línea de fuego y suele dejarte detrás de quien te perseguía. Chocar con otro avión os daña a los dos.',
            'Cada ronda dura setenta y cinco segundos y reparte puntos por derribos y por quedar en el aire; tras tres rondas se muestra el podio. Durante los primeros segundos nadie dispara y el suelo te devuelve arriba en lugar de estrellarte, para que todos tengan tiempo de despegar. Hasta cuatro pilotos en la tele con el móvil como mando, con la CPU ocupando las plazas libres; en solitario se juega con teclado, mando o tocando la pantalla para guiar el avión.',
        ],
        tips=['No subas en vertical mucho rato: en cuanto veas que el motor tose, baja el morro para recuperar velocidad.',
              'Si alguien se te pega a la cola, haz un rizo con B: sueles salir justo detrás de él.',
              'Dispara en ráfagas cortas; con la ametralladora recalentada te quedas indefenso unos segundos.'],
        players='1–4 jugadores',
    ),
    dict(
        title='Invasores a Dúo',
        genre='arcade', tags=['naves', 'cooperativo', 'invasores', 'espacio', 'vector'],
        orient='landscape', aspect='4:3', inputs='TKG',
        engine='shooter',
        cfg=dict(mode='coop', hud='tr', help='Dos naves contra la flota. Muévete con la cruceta por la franja baja y dispara con A. El escudo de energía es común: cada impacto gasta un cuarto de la barra y se recarga si nadie recibe daño. Si las naves están cerca, el rayo que las une detiene las balas. Si tu compañero cae, quédate encima de él para rescatarlo. En el móvil arrastra el dedo: la nave lo sigue y dispara sola.'),
        pad=dict(d='8', a='Fuego'),
        mp=(1, 2),
        desc=[
            'Invasores a Dúo es un matamarcianos clásico pensado para jugar en pareja: dos naves defienden juntas una base de búnkeres verdes frente a una flota de alienígenas que baja en formación, rebota de lado a lado y lanza de vez en cuando a algún atrevido en picado contra vosotros. La puntuación es común y cada oleada limpia suma un buen bonus antes de que llegue la siguiente, un poco más rápida.',
            'La gracia está en el escudo compartido. Las dos naves tiran de la misma barra de energía: cada impacto se come un cuarto y, si ninguna recibe daño durante un rato, se va recargando. Además, cuando las naves vuelan cerca aparece entre ellas un rayo que para las balas enemigas, así que cubrirse el uno al otro compensa. Si la energía se agota y una nave cae, el compañero puede rescatarla quedándose encima un segundo; si no, reaparece gastando una nave de la reserva.',
            'La partida termina si caen las dos a la vez o si la flota llega a la altura de los búnkeres. Si juegas en solitario, un piloto de la CPU hace de compañero: se coloca bajo otra columna, esquiva y viene a rescatarte. En la tele pueden jugar dos personas con el móvil como mando; en el ordenador se usan flechas y espacio, y en el móvil la nave sigue al dedo y dispara sola.',
        ],
        tips=['Volad cerca uno del otro cuando llueven balas: el rayo entre las naves las absorbe gastando muy poca energía.',
              'Los que bajan en picado dan el doble de puntos: espera a que pasen por delante y dispara.',
              'Si tu compañero cae, ve a por él enseguida: rescatarlo no gasta naves de la reserva.'],
        players='1–2 jugadores (cooperativo)',
    ),
    dict(
        title='Arena de Asteroides',
        genre='arcade', tags=['naves', 'asteroides', 'agujero-negro', 'rondas', 'vector'],
        orient='landscape', aspect='4:3', inputs='TKG',
        engine='rocks',
        cfg=dict(mode='arena', hud='tr', help='La cruceta indica hacia dónde apunta tu nave, que gira y acelera hacia allí. A dispara y B da un turbo (se recarga en 2 s). El agujero negro del centro atrae naves, rocas y balas: si tocas el núcleo, estás fuera. Cada nave tiene 3 corazones. Rondas de 60 s como máximo, 3/2/1/0 puntos por puesto y podio tras 3 rondas.'),
        pad=dict(d='8', a='Fuego', b='Turbo'),
        mp=(1, 4),
        desc=[
            'Arena de Asteroides es un todos contra todos para hasta cuatro naves en un rincón del espacio con un agujero negro justo en el centro. Las naves se mueven con inercia, como en los arcades de rocas de toda la vida, pero aquí la gravedad del agujero lo curva todo: las naves, los asteroides que orbitan alrededor y hasta las balas, que trazan arcos y pueden alcanzarte por la espalda.',
            'Cada piloto tiene tres corazones. Un disparo o un choque con una roca quita uno, y rozar el núcleo del agujero te elimina de golpe. Con el turbo puedes escapar de su atracción o cruzar la arena para acorralar a otro, pero tarda un par de segundos en recargarse. Los asteroides se parten al dispararles y los que caen al agujero reaparecen por los bordes. Además, el agujero crece durante la ronda y cada vez queda menos espacio seguro.',
            'Cada ronda termina cuando solo queda una nave o se acaba el minuto, y reparte tres, dos, uno y cero puntos según el orden de eliminación; tras tres rondas llega el podio. Al empezar hay cinco segundos de escudo y la gravedad entra poco a poco. La CPU ocupa las plazas libres y mejora con tus victorias. Se juega en la tele con el móvil como mando o en solitario con teclado, mando o controles táctiles.',
        ],
        tips=['Orbita el agujero en lugar de huir de él: la gravedad te da velocidad gratis si vas de lado.',
              'Guarda el turbo para cuando te acerques demasiado al núcleo; es la única salida rápida.',
              'Dispara con el agujero entre tú y el rival: las balas curvan y le llegan por donde no mira.'],
        players='1–4 jugadores',
    ),
]
