"""Oleada 2 — agente «precision»: puntería y habilidad (tiro, pista) y modos nuevos de darts, pool, hoop y rhythm."""

GAMES = [
    dict(
        title='Petanca de Verano',
        genre='sports-casual',
        tags=['petanca', 'turnos', 'fisica', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='tiro',
        cfg=dict(mode='petanca', hud='br', help='Petanca por turnos para 1–4. ↑ ↓ apuntan, B elige el tiro (arrimar, bombear o tirar) y mantén A: suelta con la fuerza justa. Juega quien no tiene el punto. Al final de cada mano, quien tiene la bola más cerca del boliche suma una por cada bola suya mejor que la mejor rival. Gana quien llega a 7 (o quien más tenga tras 9 manos). En el móvil, mantén el dedo hacia donde quieras tirar y suelta.'),
        pad=dict(d='8', a='Tirar', b='Estilo'),
        mp=(1, 4),
        desc=[
            'Petanca de Verano traslada al móvil y a la tele esa partida de media tarde en la plaza del pueblo, con la tierra dorada, las sombras de los árboles y las bolas de acero chocando con su clic metálico. Se ve el campo desde arriba y cada partida trae un terreno nuevo con lomas y hondonadas suaves que se notan en el dibujo: una bola que rueda por una cuesta se desvía hacia abajo, y la que cruza una hondonada gana unos metros que no esperabas. Leer el suelo es tan importante como tener buen pulso.',
            'Quien abre la mano lanza el boliche y la primera bola; después tira siempre quien no tiene el punto, así que la presión va cambiando de lado en cada lanzamiento. Hay tres formas de tirar: arrimar, que deja la bola rodando por el suelo; bombear, que la manda alta para que caiga cerca y se quede quieta; y tirar a dar, un lanzamiento directo para sacar del sitio la bola que te está quitando el punto. En la tele cada jugador usa su móvil: el joystick apunta, B cambia el estilo y A carga la fuerza. Las plazas vacías las ocupa la CPU, que calcula sus tiros con las cuestas y afina cuando le ganas.',
            'Al terminar la mano, unas líneas miden quién está más cerca y el marcador suma una por cada bola que gana. Se juega a siete puntos, con partidas de pocos minutos que siempre acaban con alguien pidiendo la revancha.',
        ],
        tips=[
            'Antes de tirar mira las sombras del terreno: la bola siempre se tuerce hacia la parte más baja.',
            'Si el rival tiene una bola pegada al boliche, a veces compensa más tirar a dar que intentar arrimar otra por delante.',
            'Bombear es más seguro en terreno irregular, porque la bola casi no rueda al caer.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Arco y Viento',
        genre='sports-casual',
        tags=['tiro-con-arco', 'punteria', 'turnos', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKMG',
        engine='tiro',
        cfg=dict(mode='arco', hud='br', help='Tres distancias (30, 50 y 70 m) y tres flechas por turno. Mantén A para tensar, mueve la mira con el joystick y suelta. El viento (manga y cifra) desvía la flecha, más cuanto más lejos, y la mira se mueve con la respiración: dispara en la calma o aguanta el aire con B unos segundos. Diana de 10 aros; la X central desempata. En el móvil, mantén el dedo, arrastra para apuntar y suelta.'),
        pad=dict(d='8', a='Tensar', b='Aire', t=1),
        mp=(1, 4),
        desc=[
            'Arco y Viento es tiro con arco al aire libre, en un prado con una diana de paja al fondo y una manga de viento que nunca está quieta. Cada jugador dispara tres flechas por turno en tres distancias, treinta, cincuenta y setenta metros, y la diana se va haciendo pequeña a medida que se aleja. Gana quien más puntos sume con sus nueve flechas; si hay empate, desempatan las X, el círculo diminuto del centro del amarillo.',
            'Apuntar no consiste solo en poner la mira en el centro. Primero hay que tensar el arco manteniendo A hasta que la barra se llena; si sueltas antes, la flecha sale floja y cae. Después la mira sube y baja con tu respiración: hay un momento de calma justo al final de cada espiración, y ese es el instante bueno. Si necesitas más tiempo puedes aguantar el aire con B, pero solo unos segundos antes de que empiece a temblar el pulso. Y luego está el viento, que empuja la flecha hacia un lado según su fuerza y la distancia: a treinta metros apenas se nota, a setenta te puede sacar del amarillo si no apuntas un poco contra él.',
            'Se juega de uno a cuatro por turnos, con el móvil como mando en la tele o con el dedo en la pantalla. La CPU ocupa las plazas libres y aprende a leer mejor el viento cada vez que le ganas.',
        ],
        tips=[
            'Mira la cifra del viento justo antes de soltar: cambia un poco mientras apuntas.',
            'A setenta metros apunta casi un aro entero contra el viento cuando sopla fuerte.',
            'No mantengas el arco tensado mucho rato: pasados unos segundos el brazo se cansa y la mira baila más.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Juegos de Pista',
        genre='sports-casual',
        tags=['atletismo', 'carreras', 'ritmo', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='pista',
        cfg=dict(mode='atletismo', hud='br', help='Cuatro pruebas: 100 m lisos, 100 m vallas, salto de longitud y jabalina, con puntos por puesto (5-3-2-1). Corre alternando I y D (← → o A/B) cuando el punto del anillo pase por la zona verde: machacar no acelera. ↑ salta las vallas; en longitud y jabalina mantén ↑ para subir el ángulo y suelta antes de la línea (pisarla es nulo). En el móvil: mitad izquierda I, derecha D y franja de arriba ↑.'),
        pad=dict(d='8', a='Pie I', b='Pie D'),
        mp=(1, 4),
        desc=[
            'Juegos de Pista reúne cuatro pruebas de atletismo en una sola competición para hasta cuatro jugadores: cien metros lisos, cien metros vallas, salto de longitud y lanzamiento de jabalina. Cada prueba reparte puntos según el puesto y al final sube al podio quien más haya sumado. Las carreras se corren a la vez, cada uno en su calle y con su color, mientras que en los saltos y los lanzamientos se hacen tres intentos por turnos y cuenta el mejor.',
            'Aquí no gana quien más rápido aporrea los botones. Cada zancada se hace con el pie contrario, izquierdo y derecho alternos, y un anillo junto a tu calle marca el ritmo: cuando el punto entra en la zona verde es el momento de pisar. Si aciertas, el corredor acelera con fuerza; si te adelantas por nervios, apenas avanzas, y si repites pie, tropiezas. Como el ritmo se acelera con la velocidad, correr bien es encontrar la cadencia y mantenerla. En las vallas hay que saltar en el sitio justo para no llevarte ninguna por delante, y en longitud y jabalina tienes que mantener arriba para elegir el ángulo y soltar sin pisar la tabla o la línea.',
            'Se juega con el móvil como mando en la tele, con teclado o con toques en la pantalla. La CPU rellena las calles libres con un ritmo más o menos fino, y mejora cuando le ganas.',
        ],
        tips=[
            'En la salida, espera al disparo: adelantarte cuesta tres décimas.',
            'Para la longitud empieza a mantener arriba un par de zancadas antes de la tabla y suelta hacia los veinte grados.',
            'En jabalina el ángulo ideal ronda los treinta y siete grados; más alto la lanzas más corta.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Dardos Cricket',
        genre='sports-casual',
        tags=['dardos', 'cricket', 'turnos', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKMG',
        engine='darts',
        cfg=dict(mode='cricket', hud='br', help='Cricket para 1–4: solo cuentan el 15, 16, 17, 18, 19, 20 y la diana. Cada número se cierra con tres marcas (el doble vale dos y el triple tres; la diana exterior una y el centro dos). Si tienes un número cerrado y algún rival no, tus marcas de más suman sus puntos. Gana quien cierra todo sin ir por detrás en puntos. Mueve la mira, mantén A para afinar el pulso y suelta para lanzar.'),
        pad=dict(d='8', a='Lanzar', t=1),
        mp=(1, 4),
        desc=[
            'Dardos Cricket es la otra gran modalidad de la diana de bar, la que se juega más con la cabeza que con la calculadora. En lugar de restar desde quinientos uno, aquí solo importan siete objetivos: los números del quince al veinte y la diana. Cada jugador tiene que cerrarlos todos consiguiendo tres marcas en cada uno, y los dobles y triples cuentan como dos y tres marcas de golpe, así que un buen triple cierra un número en un solo dardo.',
            'La gracia está en los puntos. Cuando tienes un número cerrado y algún rival todavía no, cada marca de más que le metas suma su valor en tu marcador. Eso obliga a decidir en cada turno: ¿cierras el veinte para que el otro deje de puntuar con él o sigues sumando en tu número fuerte? Gana quien cierra los siete objetivos y no va por detrás en puntos, así que no basta con correr. La pizarra de tiza muestra las marcas de todos con las barras y el círculo de toda la vida.',
            'Juegan de una a cuatro personas por turnos de tres dardos. La mira oscila y, al mantener pulsado, el pulso se estabiliza unos segundos antes de cansarse. En la tele cada uno lanza desde su móvil; en solitario la CPU ocupa las plazas y elige sus objetivos con cabeza.',
        ],
        tips=[
            'Apunta al triple del número que quieras cerrar: un solo dardo bueno vale por tres.',
            'Si vas por delante en puntos, cierra los números donde el rival puntúa; si vas por detrás, suma donde él aún no ha cerrado.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Bola Ocho Duo',
        genre='sports-casual',
        tags=['billar', 'bola-8', 'turnos', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKMG',
        engine='pool',
        cfg=dict(mode='eight', hud='br', help='Bola 8 a dos: tras la salida, la primera bola que metas te da lisas (1–7) o rayadas (9–15). Sigues tirando mientras metas de las tuyas. Falta (meter la blanca, no tocar ninguna bola o tocar primero una del rival): el otro coloca la blanca donde quiera. Gana quien, con su grupo limpio, mete la 8; meterla antes o con falta pierde. ← → apuntan (↑ ↓ ajuste fino), mantén A para la fuerza y suelta.'),
        pad=dict(d='8', a='Tirar', t=1),
        mp=(1, 2),
        desc=[
            'Bola Ocho Duo es una partida de billar americano de las de toda la vida, pensada para jugar a dos con el móvil como taco. La mesa se ve de lado a lado con su tapete verde, sus seis troneras y las quince bolas en triángulo, y la guía de tiro enseña la bola fantasma y hacia dónde saldrá la bola tocada para que cada jugada se pueda pensar. Las reglas son las de la bola ocho: la primera bola que se mete tras la salida decide quién va a por las lisas y quién a por las rayadas.',
            'Mientras metas bolas de tu grupo sigues tirando; en cuanto fallas, pasa el turno. Si cometes falta, porque se cuela la blanca, no tocas ninguna bola o tocas primero una del rival, el otro jugador recibe bola en mano y puede colocar la blanca donde más le convenga. Cuando has limpiado tu grupo toca ir a por la negra, y ahí está la tensión: si metes la ocho antes de tiempo, o en el mismo tiro se te cuela la blanca, pierdes la partida al instante.',
            'Con el mando, izquierda y derecha giran el taco, arriba y abajo lo afinan y al mantener A cargas la fuerza. En pantalla táctil basta con arrastrar hacia atrás. Si juegas solo, la CPU busca la bola más fácil para meter y afina su pulso cuando le ganas.',
        ],
        tips=[
            'No tires siempre fuerte: un golpe suave deja la blanca cerca para el siguiente tiro.',
            'Con bola en mano, coloca la blanca en línea recta con una bola tuya cerca de la tronera.',
            'Antes de ir a por la ocho, fíjate en que la blanca no vaya a seguirla hacia la misma tronera.',
        ],
        players='1–2 jugadores',
    ),
    dict(
        title='Canastas a Duelo',
        genre='sports-casual',
        tags=['baloncesto', 'versus', 'punteria', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='hoop',
        cfg=dict(mode='duel', hud='br', help='Dos canastas lado a lado y 60 segundos: gana quien más puntos meta. ← → cambian el ángulo y ↑ ↓ la fuerza (la guía de puntos enseña la parábola); A lanza. Canasta = 2 puntos, lejos o limpia (sin tocar aro) +1. Con racha de 3 el aro se mueve. En el móvil, arrastra hacia atrás y suelta en tu mitad.'),
        pad=dict(d='8', a='Lanzar'),
        mp=(1, 2),
        desc=[
            'Canastas a Duelo es el clásico reto de feria de encestar todo lo posible en un minuto, pero con un rival al lado. La pantalla se parte en dos pabellones idénticos, cada uno con su tablero, su aro y su red que se mueve de verdad cuando entra el balón, y los dos jugadores tiran a la vez. Cuando suena la bocina gana quien más puntos haya sumado, así que no hay tiempo para pensarse mucho cada lanzamiento.',
            'Cada canasta vale dos puntos, y suma uno más si tiras desde lejos o si el balón entra limpio sin tocar el aro. Los lanzamientos salen cada vez desde un sitio distinto del parqué, empezando cerca del aro y alejándose poco a poco. Con el mando, izquierda y derecha cambian el ángulo y arriba y abajo la fuerza, y una línea de puntos dibuja la parábola que va a seguir el balón para que ajustes antes de pulsar A. Si encadenas tres canastas seguidas el aro empieza a moverse de lado a lado, lo que da más emoción a las rachas.',
            'En la tele cada jugador usa su móvil como mando; en solitario te enfrentas a la CPU, que tira a su ritmo, falla más al principio y se va afinando cada vez que le ganas. Una partida dura exactamente un minuto y se juega otra enseguida.',
        ],
        tips=[
            'Ajusta primero el ángulo alto y luego la fuerza: los tiros bombeados entran limpios más a menudo.',
            'Cuando el aro se mueve, espera a que venga hacia ti antes de soltar.',
        ],
        players='1–2 jugadores',
    ),
    dict(
        title='Flechas de Baile',
        genre='party',
        tags=['ritmo', 'baile', 'musica', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='rhythm',
        cfg=dict(mode='dance', hud='br', help='Cada jugador tiene su pista con cuatro flechas. Pulsa la dirección (← ↓ ↑ →) cuando la flecha que sube llegue a su hueco. Las flechas dobles piden dos direcciones a la vez y las largas hay que mantenerlas hasta el final. PERFECTO, GENIAL, BIEN o FALLO; el combo multiplica hasta ×4. En el móvil, toca la columna de cada flecha.'),
        pad=dict(d='8', a='', t=1),
        mp=(1, 4),
        desc=[
            'Flechas de Baile es un duelo de ritmo para hasta cuatro personas en la misma canción. Cada jugador tiene su propia pista con los cuatro huecos de siempre, izquierda, abajo, arriba y derecha, y por todas suben las mismas flechas al compás de una música electrónica generada en el momento. Hay que pulsar la dirección justo cuando la flecha llega a su hueco: cuanto más clavado, mejor valoración, y encadenar aciertos sube el multiplicador hasta cuatro.',
            'La canción empieza tranquila, con pocas flechas y un pulso lento, y va acelerando poco a poco. Aparecen flechas dobles, que se pulsan a la vez como un salto sobre dos baldosas, y flechas largas que hay que mantener hasta que termine su estela. Fallar no te elimina, pero rompe el combo y deja que los demás te adelanten en el marcador, que se ve siempre debajo de cada pista con el color de cada jugador.',
            'En la tele cada uno baila con el joystick de su móvil, que para esto funciona como una alfombra en miniatura; en el ordenador se juega con las flechas del teclado y en el móvil tocando la columna de cada dirección. Las plazas que queden libres las ocupan bailarines de la CPU, que empiezan con algún despiste y afinan cuando les ganas.',
        ],
        tips=[
            'Mira las flechas cuando aún están abajo: así preparas el dedo antes de que lleguen.',
            'En las flechas largas no sueltes hasta que la estela desaparezca del todo.',
        ],
        players='1–4 jugadores',
    ),
]
