"""Oleada 3 — agente «bombas»: nuevos modos de bomber (parejas, fantasma, única), teamball (balonmano) y topdown cooperativo (castillo, horda)."""

GAMES = [
    dict(
        title='Petardo por Parejas', genre='party', tags=['petardos', 'parejas', 'equipos', 'versus', 'vector'],
        orient='auto', aspect='4:3', inputs='TKG', engine='bomber', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='parejas',
                 help='Dos contra dos: J1 y J2 forman el equipo A (izquierda) y J3 y J4 el equipo B (derecha). Muévete con el joystick o las flechas y suelta el petardo con A. Las explosiones de tu equipo no te hacen daño, así que podéis cubrir el mismo pasillo. Cada equipo defiende un carro de pólvora con tres cargas: si el rival lo revienta, la ronda es suya aunque sigáis en pie. También ganas la ronda si caen los dos rivales. Cuando tu compañero cae, tú recibes un alcance y un petardo más. Gana quien se lleve 2 rondas.',
                 rules=dict(fuse=2.4, range=2, bombs=1, speed=3.3, round=80, wins=2, crates=0.66)),
        pad=dict(d='8', a='Petardo'), mp=(1, 4),
        desc=[
            'Petardo por Parejas convierte la verbena de barrio en un pique de cuadrillas. La plaza se parte en dos: el equipo A arranca pegado a la tapia de la izquierda y el B a la de la derecha, y en el centro de cada lado descansa un carro cargado de pólvora con tres cargas a la vista. Ese carro es lo que de verdad hay que cuidar, porque una sola traca bien colocada puede decidir la ronda sin necesidad de perseguir a nadie.',
            'La diferencia con la plaza de siempre es que aquí no hay fuego amigo: las explosiones de tu compañero te atraviesan sin despeinarte, de modo que podéis taponar el mismo pasillo, encadenar mechas y avanzar pegados sin miedo a llevaros por delante. Eso abre un juego de reparto de tareas: uno abre camino entre las cajas hacia el carro rival mientras el otro se queda cerrando la vuelta por detrás. Si uno de los dos cae, el superviviente recibe un petardo más y un punto de alcance, así que quedarse solo duele, pero no es una sentencia.',
            'La ronda acaba cuando revienta un carro o cuando los dos rivales están fuera, y el primer equipo con dos rondas se lleva la noche. En el móvil se juega con el joystick y un botón, con teclado son flechas y Espacio, y en la tele hasta cuatro personas con su móvil como mando. La CPU cubre las plazas libres, cubre a su compañero, se acuerda de ir a por tu carro cuando la ronda se alarga y afina cada vez que la vences.',
        ],
        tips=['Repartíos el trabajo: uno abre cajas hacia el carro rival y el otro defiende el vuestro.',
              'Sin fuego amigo podéis encadenar dos petardos en el mismo pasillo y cerrar cualquier huida.',
              'Si te quedas solo aprovecha el alcance extra: desde más lejos alcanzas el carro sin entrar a la zona.'],
    ),
    dict(
        title='Bombas Fantasma', genre='party', tags=['petardos', 'fantasmas', 'laberinto', 'versus', 'vector'],
        orient='auto', aspect='4:3', inputs='TKG', engine='bomber', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='fantasma',
                 help='Muévete con el joystick o las flechas y suelta la bomba con A. Cuando te alcanzan no te vas: vuelves como fantasma y flotas libremente por todo el mapa atravesando cajas y muros. Con A sueltas una bomba espectral cada cinco segundos, que estalla igual que las normales. Si con ella eliminas a quien sigue vivo, resucitas en su lugar y vuelves a la partida. Gana la ronda el último con cuerpo; el primero en ganar 2 rondas se lleva la noche.',
                 rules=dict(fuse=2.4, range=2, bombs=1, speed=3.3, round=75, wins=2)),
        pad=dict(d='8', a='Bomba'), mp=(1, 4),
        desc=[
            'Bombas Fantasma se juega de noche, con la plaza teñida de azul, faroles colgando entre los balcones y una luna enorme al fondo. La primera parte es el juego de petardos de siempre: romper cajas, recoger mejoras y acorralar al vecino de enfrente. Lo que cambia es lo que pasa cuando te alcanzan, porque aquí nadie se queda mirando el resto de la ronda desde la banda.',
            'Al caer te conviertes en espíritu y flotas por donde quieras, atravesando muros, cajas y a los propios jugadores. No puedes recoger nada ni empujar bombas, pero cada cinco segundos puedes dejar caer una bomba espectral, que se comporta igual que una normal y revienta cajas y rivales. Y ahí está la revancha: si tu bomba se lleva por delante a alguien que sigue con cuerpo, cambias el sitio con él y vuelves a la partida en su casilla. Los que van ganando tienen que jugar mirando también hacia arriba, porque un fantasma rencoroso puede aparecer en cualquier rincón del mapa.',
            'Se maneja con joystick y un botón en el móvil, con flechas y Espacio en el teclado, y en la tele con hasta cuatro amigos, cada uno con su móvil. La barra de recarga del espíritu se ve en tu tarjeta, así que sabes cuándo toca atacar. Las plazas vacías las llena la CPU, que huye de las mechas y aprende de cada derrota. Las rondas son tensas hasta el último segundo y casi nunca gana quien iba primero al principio.',
        ],
        tips=['De fantasma, no sueltes la bomba a bulto: espera a que alguien esté encerrado entre cajas.',
              'Si vas vivo, no te confíes en los rincones: los espíritus atraviesan los muros y llegan a cualquier parte.',
              'Rompe cajas pronto; con más alcance te quitas de encima a un fantasma antes de que recargue.'],
    ),
    dict(
        title='Bomba Única', genre='party', tags=['petardos', 'patata-caliente', 'versus', 'vector'],
        orient='auto', aspect='4:3', inputs='TKG', engine='bomber', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='unica',
                 help='En todo el mapa solo hay una bomba encendida. Camina sobre ella para cogerla: la llevas en alto y el número te dice los segundos que quedan. Con A la lanzas hacia donde miras y resbala hasta chocar con algo o con alguien, que se queda con ella. Con B la sueltas a tus pies. Si te estalla encima, quedas fuera; entonces aparece otra bomba en el centro con la mecha un poco más corta y más alcance. Gana la ronda el último en pie; a 2 rondas ganadas se acaba la partida.',
                 rules=dict(fuse=5.2, range=2, bombs=0, speed=3.4, round=90, wins=2, crates=0.5)),
        pad=dict(d='8', a='Lanzar', b='Soltar'), mp=(1, 4),
        desc=[
            'Bomba Única le da la vuelta al juego de petardos: en el mapa entero hay una sola bomba encendida y no se puede apagar. Quien la lleva la carga en alto con el número de segundos bien visible sobre la cabeza, y el resto corre a esconderse entre las cajas. Es la patata caliente de toda la vida, pero con pasillos, columnas y un cronómetro que quema.',
            'Cogerla es tan fácil como pisar su casilla, y quitártela de encima tiene dos formas. Con A la lanzas hacia donde miras y la bomba resbala en línea recta hasta chocar con una caja, una columna o un rival, y quien recibe el golpe se queda con ella; con B la sueltas a tus pies, que sirve para dejarla justo en un cruce por el que va a pasar alguien. Lo interesante es que el que la lleva no puede quedarse quieto ni esconderse: los demás le esquivan y él tiene que perseguir a alguien con la mecha consumiéndose.',
            'Cuando la bomba se lleva a alguien por delante aparece otra en el centro, con la mecha algo más corta y un alcance mayor, así que cada ronda se acelera sola hasta quedar dos jugadores dando vueltas alrededor de una columna. En el móvil se juega con joystick y dos botones, con teclado son flechas, Espacio y X, y en la tele con hasta cuatro amigos. La CPU que rellena huecos apunta a quien tiene más cerca, entra en pánico cuando quedan dos segundos y mejora con cada derrota.',
        ],
        tips=['No lances la bomba a bulto: mira que no haya una caja en medio, se parará ahí y volverá a ser de nadie.',
              'Si la llevas, persigue por pasillos estrechos; en campo abierto es imposible tocar a nadie.',
              'Sin bomba, quédate a dos casillas del portador: lo bastante cerca para vigilarlo y lo bastante lejos para huir.'],
    ),
    dict(
        title='Balonmano Relámpago', genre='sports-casual', tags=['balonmano', 'equipos', 'versus', 'vector'],
        orient='auto', aspect='fill', inputs='TKG', engine='teamball', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='balonmano', time=120,
                 help='Dos jugadores de campo por equipo más un portero que lleva siempre la CPU. Mueve con el joystick o las flechas. Con balón, A pasa al compañero y B mantenido carga el lanzamiento; sin balón, A pide el pase o cambia de jugador y B intenta robar. No se puede entrar en el área semicircular: si te acercas, el propio terreno te empuja fuera, así que hay que tirar desde el borde. Dos minutos de partido; si hay empate, gol de oro.'),
        pad=dict(d='8', a='Pase', b='Tiro'), mp=(1, 4),
        desc=[
            'Balonmano Relámpago es un partido corto y eléctrico en una pista de resina azul con las áreas pintadas de blanco y las marcas de siete metros bien visibles. Dos jugadores de campo por bando más un portero que siempre lleva la máquina, dos minutos de reloj y unas porterías anchas en las que casi todo lo que llega con potencia acaba dentro.',
            'La regla que manda es el área: ese semicírculo delante de cada portería está prohibido para los jugadores de campo, y no hace falta que nadie pite nada porque la propia pista te aparta si intentas meter el pie. Eso obliga a lanzar desde el borde, buscando ángulo, o a pasar rápido de un lado a otro hasta que el portero se descoloca. Con el balón, A pasa y B mantenido carga el disparo, que sale tanto más fuerte cuanto más tiempo aguantes; sin balón, A te cambia al jugador mejor situado y B es la entrada para robar.',
            'El portero sale a cortar los balones que caen en su área y saca rápido hacia el compañero más adelantado, así que un lanzamiento parado se convierte en un contragolpe en dos segundos. En el móvil se juega con joystick y dos botones, con teclado flechas, Espacio y X, y en la tele hasta cuatro personas, rosas contra azules. La CPU rellena lo que falte, cierra líneas de pase y se vuelve más rápida cada vez que la ganas. Si los dos minutos terminan en empate, el siguiente gol decide.',
        ],
        tips=['No te empeñes en acercarte: el área te expulsa. Tira desde el borde y busca el palo largo.',
              'Un pase rápido de banda a banda deja al portero a contrapié mejor que cualquier cañonazo.',
              'Carga el tiro solo lo justo: mientras cargas estás quieto y la defensa rival llega a taparte.'],
    ),
    dict(
        title='Castillo de Dos', genre='arcade', tags=['cooperativo', 'mazmorra', 'llaves', 'equipos', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG', engine='topdown', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='castillo',
                 help='Cooperativo para uno a cuatro. Elige clase con ← → y confirma con A. Te mueves con el joystick o las flechas y atacas solo al enemigo más cercano; A lanza la habilidad de tu clase y B es una voltereta. Si un compañero cae, quédate a su lado para levantarlo. Al limpiar la sala aparecen dos losas de presión: una está encerrada tras una reja y la otra fuera, y hay que pisarlas a la vez para que la reja suba y se abra la puerta de salida. Jugando solo, la CPU se coloca en la losa que quede libre.'),
        pad=dict(d='8', a='Habilidad', b='Rodar'), mp=(1, 4),
        desc=[
            'Castillo de Dos es una incursión cooperativa por las salas de un castillo viejo, con suelo de ladrillo, antorchas en las paredes y esqueletos, murciélagos y espectros que salen de las esquinas. Cada jugador escoge clase antes de entrar (caballero, arquera, maga o clérigo) y el grupo avanza sala a sala; los ataques básicos salen solos contra el enemigo más cercano, así que lo que decide todo es colocarse bien, esquivar rodando y soltar la habilidad en el momento justo.',
            'La gracia está en la cerradura del castillo. Cuando la sala queda limpia no se abre la puerta sin más: aparecen dos losas de presión, una dentro de una alcoba cerrada por una reja y otra fuera, y la reja solo sube mientras alguien mantiene pisada la de fuera. Hay que entrar con la reja levantada, pisar la de dentro y coincidir con el compañero un instante para que el mecanismo se quede abierto. Es una llave que exige dos personas, y por eso la sala no se puede terminar corriendo a lo loco.',
            'Jugando solo no te quedas atascado: la CPU se encarga de la losa que tú no ocupes y entiende cuál le toca según dónde estés. Quien se queda sin corazones no muere, se queda tendido y cualquier compañero que aguante a su lado unos segundos lo levanta; si caen todos a la vez, la expedición acaba. Cada cinco salas hay un jefe, tras cada sala el grupo elige una mejora común y el número de enemigos crece con el número de héroes vivos, así que jugar acompañado no lo hace más fácil, solo más ruidoso.',
        ],
        tips=['Antes de pisar la losa de fuera comprueba dónde está tu compañero: la reja solo sube mientras la mantienes.',
              'La voltereta es invulnerable un instante; úsala para cruzar entre esqueletos en vez de para huir.',
              'Si alguien cae justo antes de abrir la reja, levantadlo primero: la losa necesita dos personas de pie.'],
    ),
    dict(
        title='Asedio Zombi Coop', genre='arcade', tags=['cooperativo', 'zombis', 'oleadas', 'supervivencia', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG', engine='topdown', players='1–4 jugadores',
        cfg=dict(hud='bl', mode='horda',
                 help='Cooperativo para uno a cuatro. Elige clase con ← → y confirma con A. Muévete con el joystick o las flechas; el ataque sale solo contra el zombi más cercano, A lanza la habilidad de tu clase y B es una voltereta. Los zombis entran por los bordes del corral sin parar hasta completar la oleada. Si un compañero cae, quédate a su lado unos segundos para levantarlo; si caéis todos a la vez, se acabó. Entre oleada y oleada elegís una mejora para todo el equipo, y cada cinco oleadas aparece un bruto.'),
        pad=dict(d='8', a='Habilidad', b='Rodar'), mp=(1, 4),
        desc=[
            'Asedio Zombi Coop encierra a un grupo de hasta cuatro supervivientes en un corral de tierra rodeado de vallas y cajas, con los muertos entrando por todos los bordes a la vez. No hay puerta por la que huir ni sala que limpiar con calma: la oleada solo termina cuando ha entrado y caído el último zombi de la cuenta, así que toca aguantar la posición y repartirse los flancos.',
            'Cada superviviente elige clase antes de empezar. El caballero aguanta los golpes y barre a su alrededor, la arquera dispara rápido y suelta una lluvia de flechas, la maga lanza orbes que atraviesan a varios enemigos y congela a los que tiene pegados, y el clérigo reparte mazazos y con su plegaria cura y pone en pie a los caídos. Los ataques básicos son automáticos contra el zombi más cercano: lo que decide la partida es la colocación, las volteretas para salir de un corro y el momento exacto de la habilidad.',
            'Quien se queda sin corazones cae al suelo pidiendo ayuda y cualquier compañero que aguante unos segundos a su lado lo levanta con media vida; si caen todos a la vez, el asedio termina. Entre oleadas el equipo elige una mejora común entre tres cartas, y cada cinco oleadas llega un bruto enorme que obliga a repartir el fuego. El número de zombis y el ritmo al que entran crecen con el número de héroes vivos, de modo que jugando solo la CPU te acompaña y la horda se ajusta a vosotros. Se juega con joystick y dos botones en el móvil, con teclado, o en la tele con hasta cuatro móviles.',
        ],
        tips=['No os juntéis los cuatro en una esquina: los zombis entran por todos los bordes y os rodean.',
              'Levantar a un compañero caído cuesta unos segundos; hacedlo entre dos oleadas de entradas, no en mitad del corro.',
              'La voltereta atraviesa el cerco: úsala para salir cuando te rodeen en vez de intentar pegar hacia fuera.'],
    ),
]
