"""Oleada 3 — cartas y farol: siete y medio, escoba y burro (motor `baraja`); dados mentirosos, compartir o robar y combinación oculta (motor `farol`)."""
PAD_C = dict(d='8', a='Elegir', b='Confirmar', t=1)
PAD_B = dict(d='h', a='¡Burro!', b='Pasar', t=1)
PAD_F = dict(d='8', a='Aceptar', b='Atrás', t=1)

GAMES = [
    dict(
        title='Siete y Medio', genre='strategy-cards', tags=['siete-y-medio', 'baraja-espanola', 'cartas', 'banca', 'familia', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='baraja', pad=PAD_C, mp=(1, 4), players='1–4 jugadores',
        cfg=dict(mode='siete', hud='tr', help='Pide carta con A o plántate con B (en el móvil, con los botones de tu mano). Cada carta suma su número y las figuras (sota, caballo, rey) valen medio punto. Pasarte de 7,5 es perder. Cuando todos se plantan juega la banca: empate a favor de la banca. Quien hace 7,5 exactos cobra doble y se queda la banca. Juego sin apuestas de dinero: se juega con fichas de la partida.'),
        desc=[
            'El siete y medio es el juego de cartas de sobremesa por excelencia en España: sencillo de explicar en medio minuto y capaz de tener a toda la mesa aguantando la respiración. Se juega con la baraja española de cuarenta cartas, cada una vale su número y las tres figuras —sota, caballo y rey— medio punto. El objetivo es acercarse lo máximo posible a siete y medio sin pasarse, porque quien se pasa pierde al momento y no hay vuelta atrás.',
            'La banca reparte una carta tapada a cada jugador y luego, uno por uno, cada cual decide si pide otra o se planta. Cuando todos han terminado, la banca descubre y juega su mano: si se pasa, paga a todos los que siguen vivos; si no, se lleva lo de quienes tengan menos o igual que ella, porque el empate es siempre suyo. Hacer siete y medio clavados cobra el doble y además te da la banca en la ronda siguiente, que es donde está el verdadero premio: llevar la banca significa mandar en la mesa hasta que alguien te la quite.',
            'En esta versión se juega con fichas de la partida, sin dinero de ninguna clase, y la mesa termina cuando alguien deja secos a los demás o se acaban las manos pactadas. La CPU ocupa las sillas vacías y juega con criterio: se planta antes cuando tiene poco que perder y se arriesga cuando va por detrás, y aprieta más a medida que le vas ganando partidas.',
            'En el modo tele cada jugador ve sus cartas solo en su móvil, así que nadie puede espiar la mano del vecino: la pantalla grande enseña el tapete, las cartas boca abajo, las fichas y el turno. Sin tele juegas tú contra la CPU con la mano a la vista, tocando la pantalla o con las teclas.',
        ],
        tips=['Con 5 o 5,5 la decisión es fina: piensa en cuántas cartas pequeñas quedan por salir antes de pedir.', 'Si la banca ya se ha pasado dos veces seguidas, arriésgate menos: te basta con sobrevivir para cobrar.', 'Cuando llevas la banca puedes plantarte más bajo, porque el empate lo ganas tú.'],
    ),
    dict(
        title='La Escoba', genre='strategy-cards', tags=['escoba', 'escoba-de-15', 'baraja-espanola', 'cartas', 'familia', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='baraja', pad=PAD_C, mp=(1, 4), players='1–4 jugadores',
        cfg=dict(mode='escoba', hud='tr', help='En tu turno echas una carta: si con ella y una o varias de la mesa sumas 15, te las llevas todas. Si además dejas la mesa vacía es escoba y suma un punto extra. Las figuras valen 8 (sota), 9 (caballo) y 10 (rey). Elige tu carta con la cruceta y A, y luego marca las cartas de la mesa que quieres. Al final se cuenta: más cartas, más oros, el siete de oros (velo) y más sietes, un punto cada cosa, más las escobas. Se juega a 21.'),
        desc=[
            'La escoba de quince es de esos juegos que se aprenden en una tarde y no se olvidan nunca. Se reparten tres cartas a cada jugador y cuatro boca arriba en la mesa. En tu turno echas una carta: si sumando esa carta con una o varias de las que hay en la mesa llegas exactamente a quince, te llevas todas esas cartas a tu montón; si no, tu carta se queda en la mesa esperando a que alguien la aproveche.',
            'Las cartas valen su número y las figuras suben la cuenta: la sota ocho, el caballo nueve y el rey diez, así que un rey solo necesita un cinco y un as ya casi nunca sirve solo. Cuando una jugada deja la mesa completamente vacía, eso es una escoba: un punto redondo y una pequeña celebración. Cuando todos se quedan sin cartas se reparten tres más, y al terminar la baraja las cartas que quedan en la mesa se las lleva quien capturó por última vez.',
            'El recuento final es lo que convierte la escoba en un juego de estrategia y no de suerte: un punto para quien tenga más cartas, uno para quien tenga más oros, uno para el siete de oros —el velo, la carta más peleada de la baraja— y uno para quien reúna más sietes, además de un punto por cada escoba. Se juega a veintiún puntos, así que una mano no decide nada y se puede remontar.',
            'La CPU calcula todas las combinaciones posibles y valora lo que deja en la mesa antes de tirar, pero empieza floja y se vuelve más cuidadosa según le ganas. En la tele cada jugador ve su mano solo en su móvil y la pantalla grande muestra la mesa, los montones y el recuento de la ronda.',
        ],
        tips=['No dejes en la mesa cartas que sumen quince con un rey o un siete: son las más fáciles de recoger para el siguiente.', 'Persigue el siete de oros aunque te cueste una captura pequeña: el velo vale un punto entero.', 'Guarda un as o un dos para el final de la mano: son las cartas que rematan escobas cuando queda poco en la mesa.'],
    ),
    dict(
        title='El Burro', genre='party', tags=['burro', 'cartas', 'reflejos', 'baraja-espanola', 'fiesta', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='baraja', pad=PAD_B, mp=(2, 4), players='2–4 jugadores',
        cfg=dict(mode='burro', hud='tr', help='Todos a la vez: elige una carta con ← → y pásala a tu izquierda con B (o tócala), mientras recibes las del vecino; nadie acumula más de cinco. En cuanto tengas cuatro iguales pulsa A. El primero que pulsa debe tener el póker o se lleva una letra; los demás pulsan al verlo y el último se lleva letra. Cinco letras son BURRO: gana quien menos letras tenga.'),
        desc=[
            'El burro es un juego de patio de colegio que funciona igual de bien en una sobremesa de adultos: nadie espera turno, todos pasan cartas a la vez y la mesa entera está pendiente de las manos de los demás. Cada jugador recibe cuatro cartas del mismo grupo de figuras y números, y el objetivo es reunir las cuatro del mismo valor pasando al vecino de la izquierda la que no te sirve, una y otra vez, cada vez más deprisa.',
            'El momento clave llega cuando alguien completa su póker: pulsa, y a partir de ahí es una carrera de reflejos, porque en cuanto uno pulsa todos los demás deben pulsar inmediatamente. El último en reaccionar se lleva una letra. Si alguien pulsa por error sin tener las cuatro cartas iguales, la letra se la queda él, así que conviene mirar antes de lanzarse. Cinco letras deletrean la palabra burro y dejan a ese jugador fuera de la pelea por la victoria.',
            'La versión de aquí mantiene el ritmo original: las cartas se pasan sin turnos, con un aviso de cuenta atrás antes de cada ronda para que nadie empiece en desventaja, y los primeros segundos nunca penalizan. Las CPU pasan cartas a un ritmo humano y reaccionan con un retraso que se va acortando según ganas partidas, así que la primera partida se gana fácil y la quinta ya cuesta.',
            'En la tele es donde brilla: la pantalla grande muestra solo el reverso de las manos rivales y el aviso de quién ha pulsado, y cada jugador ve sus cuatro cartas únicamente en su móvil, con un botón grande de burro siempre a mano. Sin tele juegas contra las CPU con tu mano a la vista.',
        ],
        tips=['No mires solo tus cartas: si alguien deja de pasar de repente, probablemente ya tenga el póker.', 'Pasa rápido lo que no te sirve aunque no tengas plan: acumular cartas muertas solo te frena.', 'Ten el dedo cerca del botón de burro desde el principio de la ronda; se gana por décimas.'],
    ),
    dict(
        title='Dados Mentirosos', genre='party', tags=['farol', 'dados', 'mentiras', 'apuestas', 'fiesta', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='farol', pad=PAD_F, mp=(2, 4), players='2–4 jugadores',
        cfg=dict(mode='dados', help='Cada uno ve sus dados solo en su móvil. Se apuesta por turnos cuántos dados hay en toda la mesa de un valor, y cada apuesta debe superar a la anterior (más cantidad, o igual cantidad con valor mayor). Sube con la cruceta y A, o grita ¡Dudo! con B. Si la apuesta no se cumple pierde un dado quien apostó; si se cumple, quien dudó. Sin dados, fuera. Sin apuestas de dinero.'),
        desc=[
            'Los dados mentirosos son el juego de farol más directo que existe: cinco dados por cabeza escondidos bajo un cubilete y una mesa entera intentando adivinar qué hay debajo de los cubiletes de los demás. Cada ronda empieza con todos agitando a la vez y mirando en secreto su tirada; a partir de ahí se apuesta en voz alta sobre el total de la mesa, no sobre lo tuyo.',
            'Una apuesta es siempre una cantidad y un valor: tres cuatros, cinco seises. El siguiente jugador tiene que subir, ya sea diciendo más dados del mismo valor o la misma cantidad de un valor más alto, o bien plantarse y gritar que duda. Entonces se levantan todos los cubiletes y se cuenta: si hay al menos tantos dados como decía la apuesta, el que dudó pierde un dado; si no los hay, lo pierde el fanfarrón que apostó. Quien se queda sin dados abandona la mesa y el último que conserva alguno gana.',
            'Todo el interés está en calcular sin que se note: con veinte dados en la mesa la media dice que hay unos tres de cada valor, así que apostar cuatro es razonable, apostar siete es un farol y apostar dos es regalar el turno. Las CPU estiman esa probabilidad contando sus propios dados, se tiran faroles calculados y dudan cuando la cuenta se dispara; empiezan siendo confiadas y se vuelven más agudas con cada victoria tuya.',
            'Es un juego pensado para la tele: la pantalla grande enseña los cubiletes, la última apuesta y quién ha dudado, mientras cada jugador ve su tirada exclusivamente en su móvil. No hay dinero ni apuestas reales de ninguna clase, solo dados y cara de póker.',
        ],
        tips=['Con muchos dados en la mesa, apostar cerca de un tercio del total del valor que más repitas suele ser seguro.', 'Fíjate en quién sube poco: el que apuesta lo mínimo casi nunca tiene ese valor.', 'Cuando quedan pocos dados, dudar pronto es mejor que subir a ciegas.'],
    ),
    dict(
        title='Compartir o Robar', genre='party', tags=['compartir-o-robar', 'farol', 'dilema', 'psicologia', 'fiesta', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='farol', pad=PAD_F, mp=(2, 4), players='2–4 jugadores',
        cfg=dict(mode='reparto', help='Cada ronda aparece un cofre con un montón de monedas y todos eligen en secreto en su móvil: Compartir o Robar. Si todos comparten, el cofre se reparte a partes iguales entre todos. Si algunos roban, los ladrones se reparten el cofre entero y los demás se quedan sin nada. Y si roban todos, el cofre se pierde y nadie gana. Se juegan seis rondas y el último cofre vale el doble. Gana quien acumule más monedas. Elige con la cruceta y confirma con A; si no eliges en 22 segundos, se cuenta como Compartir.'),
        desc=[
            'Compartir o robar es el dilema del prisionero convertido en juego de sobremesa, y no hace falta saber nada de teoría de juegos para pasarlo bien: basta con mirar a la cara a quien tienes enfrente y decidir si te fías. Cada ronda aparece un cofre con una cantidad de monedas a la vista y todos los jugadores eligen en secreto, a la vez, entre compartir el botín o quedárselo.',
            'Las cuentas son crueles en su sencillez. Si todo el mundo comparte, el cofre se reparte a partes iguales y todos salen ganando algo. Si solo una persona roba, esa persona se lleva el cofre entero y los demás se quedan a cero mirando. Si roban dos o tres, se lo reparten entre ellos y los que confiaron pagan la ingenuidad. Y si roban absolutamente todos, el cofre se pierde: nadie se lleva nada y la mesa entera ha desperdiciado la ronda. Después de cada decisión se revelan todas las elecciones a la vez, que es el momento por el que se juega.',
            'Son seis rondas y el último cofre vale el doble, de modo que quien va perdiendo siempre tiene una última oportunidad de darle la vuelta a la partida con una traición bien colocada. Entre medias hay tiempo de sobra para acuerdos hablados que luego nadie está obligado a cumplir, que es exactamente la gracia del asunto.',
            'Las CPU tienen memoria: guardan quién les ha robado antes y devuelven el golpe, con un punto de imprevisibilidad para que no se vuelvan predecibles. En la tele cada jugador decide en su móvil sin que se vea nada en la pantalla grande hasta la revelación; sin tele juegas contra tres CPU que negocian a su manera.',
        ],
        tips=['Robar en la primera ronda es tentador pero marca la partida: las CPU y la gente se acuerdan.', 'Si dos rivales ya se han traicionado entre ellos, compartir suele rentar más que arriesgarse.', 'Guarda el robo para el cofre doble del final, cuando ya no hay tiempo de vengarse.'],
    ),
    dict(
        title='Combinación Oculta', genre='puzzle', tags=['mastermind', 'deduccion', 'logica', 'colores', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='farol', pad=PAD_F, mp=(1, 2), players='1–2 jugadores',
        cfg=dict(mode='codigo', help='Hay una combinación secreta de cuatro fichas de color. Elige un color con ← → y colócalo con A; con B borras la última ficha. Al completar las cuatro se comprueba: una clavija negra por cada ficha del color correcto en la posición correcta, y una blanca por cada color correcto en posición equivocada (sin decirte cuál es cuál). Tienes diez intentos. En el modo de dos jugadores gana quien acierte antes su propia combinación; si nadie acierta, gana quien más clavijas negras haya sacado.'),
        desc=[
            'Combinación Oculta es el clásico juego de deducción de fichas de colores, ese tablero de clavijas que estuvo en todas las casas y que sigue siendo uno de los mejores ejercicios de lógica que se han inventado. La máquina esconde una combinación de cuatro colores y tú tienes que descubrirla a base de intentos, leyendo con cuidado las pistas que devuelve cada uno.',
            'Las pistas son las de siempre y siguen siendo lo más ingenioso del juego: una clavija negra por cada ficha que has puesto del color correcto y en el sitio correcto, y una blanca por cada color que está en la combinación pero en otra posición. Lo que nunca se te dice es a qué ficha corresponde cada clavija, y ahí está todo el trabajo: cruzar la información de varios intentos hasta que solo queda una posibilidad. Los primeros niveles usan cuatro colores para que se aprenda el mecanismo, y van subiendo hasta seis, donde hace falta pensar de verdad.',
            'En solitario es una partida tranquila de diez intentos contra el reloj de tu propia cabeza; en el modo de dos jugadores se convierte en una carrera, porque cada uno tiene su combinación y su tablero, y gana quien resuelva primero. Si a nadie le da tiempo, se mira quién había llegado más lejos.',
            'Cada jugador ve su tablero y su historial de intentos en su móvil cuando se juega en la tele, y la pantalla grande muestra los dos tableros con las clavijas, pero nunca la combinación secreta hasta que la ronda termina. Sin tele juegas con el tablero completo en pantalla.',
        ],
        tips=['Empieza con dos colores repetidos dos veces: descubres más con menos información.', 'Anota mentalmente los colores descartados antes de mover posiciones; ordenar viene después de saber qué hay.', 'Si un intento da cuatro clavijas blancas, tienes todos los colores: solo te queda colocarlos.'],
    ),
]
