"""Oleada 3 — agente «honda»: motor nuevo de tirachinas y proyectiles (honda) y modos nuevos de platform, frog y maze."""

GAMES = [
    dict(
        title='Honda de Frutas',
        genre='arcade',
        tags=['tirachinas', 'fisica', 'punteria', 'niveles', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKMG',
        engine='honda',
        cfg=dict(mode='frutas', hud='br', help='Tira frutas con la honda y derriba las fortalezas hasta que no quede ninguna verdura. En el móvil: arrastra hacia atrás desde la honda y suelta; cuanto más estiras, más fuerza. Con teclado o mando: ↑ ↓ cambian el ángulo y mantienes A para cargar la fuerza; al soltar sale la fruta. Mientras vuela, toca la pantalla (o pulsa B) para usar su truco: la cereza se divide en tres, la naranja acelera, la sandía se desploma de golpe y el kiwi rebota hacia arriba. Cada fruta que te sobra al terminar el nivel suma puntos extra.'),
        pad=dict(d='8', a='Tirar', b='Truco', t=1),
        mp=None,
        desc=[
            'En Honda de Frutas se han atrincherado las verduras del huerto y tú respondes desde el otro lado del prado con una honda de madera y una cesta de fruta madura. Cada nivel presenta una construcción distinta hecha de tablones, bloques de hielo y sillares de piedra, con tomates, berenjenas, brócolis y pimientos encaramados donde más cuesta alcanzarlos. No basta con acertar: lo divertido es encontrar el punto flaco de la estructura para que se venga abajo entera y arrastre a media docena de verduras de una sola vez.',
            'La física está hecha a medida para este motor: cada pieza tiene su peso, su resistencia y su rozamiento, así que la madera se agrieta, el hielo estalla al primer golpe fuerte y la piedra aguanta casi todo pero pesa muchísimo cuando cae. Las piezas se van resquebrajando a la vista, y una torre a la que le quitas una pata se desploma hacia el lado que le pide su propio peso. Las cuatro frutas se comportan de forma distinta y cada una tiene un truco que se activa en pleno vuelo, lo que convierte un tiro fallado en una segunda oportunidad si lo usas en el momento justo.',
            'Todos los niveles se generan al vuelo y antes de dártelos el juego los resuelve él mismo por simulación: si no consigue terminarlos con una fruta menos de las que te da, los descarta y prueba otro. Así siempre hay solución y siempre te sobra margen. El primer nivel es casi un tutorial, con dos verduras a la vista y frutas de sobra, y a partir de ahí crecen las torres, aparecen la piedra y los pisos altos, y hay que empezar a pensar antes de estirar la goma.',
        ],
        tips=[
            'Apunta a la base de las torres: quitar una pata derriba mucho más que acertar arriba del todo.',
            'La sandía es lenta pero demoledora; guárdala para la piedra y usa la cereza contra el hielo.',
            'Si vas a fallar por poco, toca en pleno vuelo: la naranja acelera y el kiwi rebota hacia arriba.',
        ],
        players='1 jugador',
    ),
    dict(
        title='Caseta de Tiro',
        genre='arcade',
        tags=['feria', 'punteria', 'versus', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKMG',
        engine='honda',
        cfg=dict(mode='caseta', hud='br', help='Sesenta segundos de tiro de feria para 1–4. Mueve la mira con el joystick (o las flechas; en un jugador también con el dedo) y dispara con A. Los patos de la fila de arriba valen más que los de abajo, las botellas suman al caer y la estrella dorada da 500 puntos. Tienes seis perdigones: se recargan solos al gastarlos o antes con B. Gana quien más puntos sume cuando suene la campana; las plazas libres las ocupa la CPU.'),
        pad=dict(d='8', a='Disparar', b='Recargar'),
        mp=(1, 4),
        desc=[
            'Caseta de Tiro es la barraca de feria de toda la vida: toldo de rayas, guirnalda de bombillas y tres filas de patos de hojalata que cruzan sin parar de lado a lado. Delante, tres estantes con pirámides de botellas que se derrumban de verdad cuando les aciertas, porque caen con la misma física de cajas que usa el resto del motor. Y de vez en cuando aparece una estrella dorada que se pasea flotando por encima de todo y vale más que ningún pato.',
            'Cada jugador tiene su escopeta de feria en la barra y su mira del color de su mando. Los perdigones no van en línea recta: caen un poco, así que a los patos lejanos hay que adelantarles el tiro, y a las botellas conviene apuntarles a la base para que arrastren a las de arriba. Seis perdigones por cargador obligan a elegir: puedes vaciar el cargador a lo loco y esperar la recarga o recargar tú antes de que llegue el pato bueno. Las filas de arriba puntúan más porque son las más rápidas y las más estrechas.',
            'Se juega en la tele con hasta cuatro móviles de mando, o tú solo contra la CPU en el móvil. La CPU falla bastante al principio y va afinando la puntería cada vez que le ganas una partida, así que el reto crece contigo. Al sonar la campana de los sesenta segundos sale la clasificación con los puntos de cada uno.',
        ],
        tips=[
            'Adelanta el tiro a los patos: los perdigones caen y los de la fila de arriba van rápidos.',
            'Dispara a la botella de abajo de la pirámide: se llevará por delante a las demás.',
            'Si ves la estrella dorada, deja los patos: 500 puntos valen más que cinco patos seguidos.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Tejados Ninja',
        genre='platformer',
        tags=['ninja', 'versus', 'plataformas', 'vector'],
        orient='landscape', aspect='16:9', inputs='TKG',
        engine='platform',
        cfg=dict(mode='tejados', theme='night', help='Duelo de ninjas sobre los tejados de la ciudad para 1–4. Muévete con el joystick o las flechas, salta con A y lanza una estrella con B (tres seguidas y luego hay que esperar). Los tejados se resquebrajan bajo tus pies: si te quedas parado en uno, se cae contigo. El que recibe una estrella sale despedido; el último en pie gana la ronda y el que más rondas gane, la partida. En el móvil, sin mando, toca la mitad de la pantalla hacia la que quieres ir y desliza hacia arriba para saltar.'),
        pad=dict(d='h', a='Saltar', b='Estrella'),
        mp=(1, 4),
        desc=[
            'Tejados Ninja transcurre de noche, sobre las tejas de una ciudad dormida, con la luna al fondo y las siluetas de las torres recortadas contra el cielo. Hasta cuatro ninjas saltan de tejado en tejado mientras las tejas se van resquebrajando bajo sus pies: cada tejado aguanta un rato el peso de quien está encima, cruje, se inclina y acaba cayendo al vacío. Quedarse quieto no es una opción, y el tejado más cómodo es siempre el que está a punto de desaparecer.',
            'Además de correr y saltar hay estrellas arrojadizas. Puedes lanzar tres seguidas antes de que el brazo necesite un respiro, y quien recibe una sale despedido en la dirección del impacto, lo que muchas veces vale más que un empujón: un rival en el aire sobre un hueco ya no vuelve. Los saltos llevan margen de coyote y memoria de salto, así que se puede apurar el borde sin que el juego te castigue por unos milisegundos, y nadie puede lanzar estrellas durante los primeros segundos de cada ronda para que a nadie lo eliminen antes de tocar el suelo.',
            'La partida son tres rondas y en cada una se reparten puntos según el orden en que van cayendo: el último en pie se lleva la ronda. Si juegas solo, la CPU ocupa las otras plazas con un estilo prudente que mejora cuando le vas ganando. En la tele cada jugador usa su móvil como mando, y las tejas rotas van dejando huecos que cambian el mapa cada ronda.',
        ],
        tips=[
            'No te pares: el tejado en el que estás ya está contando sus segundos.',
            'Lanza la estrella cuando el rival esté en el aire; con el empujón no llegará al otro lado.',
            'Guarda una estrella para defenderte: quedarte a cero con alguien encima es mala idea.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Cruce sin Fin',
        genre='arcade',
        tags=['cruzar', 'reflejos', 'versus', 'vector'],
        orient='portrait', aspect='4:3', inputs='TKG',
        engine='frog',
        cfg=dict(mode='infinito', help='Cruza carreteras y ríos que no se acaban nunca, hasta cuatro a la vez. Toca, desliza o usa las flechas para saltar una casilla en cada dirección; en el mando, el joystick. Sobre el río hay que ir encima de troncos y tortugas, y en la carretera esquivar los coches. La pantalla sube sola poco a poco: quien se queda atrás y sale por abajo queda eliminado. Gana quien llegue más lejos; las plazas libres las ocupa la CPU.'),
        pad=dict(d='8', a='Saltar', t=1),
        mp=(1, 4),
        desc=[
            'Cruce sin Fin toma el cruce de carretera de toda la vida y le quita el final: no hay charcas que llenar ni nivel que superar, solo filas y filas que se generan sin parar mientras subes. Carreteras con coches, camiones y bólidos, ríos con troncos y tortugas que se sumergen, y de vez en cuando una mediana de hierba para respirar. Cuanto más arriba llegas, más juntos van los vehículos y más rápido pasan, así que la partida se convierte en un pulso entre la prisa y la paciencia.',
            'La gracia está en que caben hasta cuatro ranas a la vez en la misma pantalla, cada una de su color. No hay colisiones entre vosotros, pero sí una cámara compartida que sube sola y cada vez más deprisa: si te quedas rezagado mirando pasar los coches, el borde de abajo te alcanza y quedas eliminado. Eso obliga a arriesgar cuando alguien tira hacia arriba, y convierte cada tronco que pasa en una decisión rápida. Si te atropellan o te caes al agua, vuelves a aparecer un poco más abajo con un par de segundos de inmunidad, hasta que te quedas sin intentos.',
            'Se puntúa por la fila más alta a la que llegas, así que el marcador va subiendo mientras avanzas. Cuando cae el último, la clasificación ordena a todos por distancia. Jugando solo, la CPU ocupa las otras plazas y cruza con prudencia, un poco mejor cada vez que le ganas una partida.',
        ],
        tips=[
            'En el río mira hacia dónde va el tronco antes de saltar: te lleva mientras esperas.',
            'Las tortugas que sueltan burbujas están a punto de sumergirse; no te quedes en ellas.',
            'Si la cámara te está comiendo, cruza por detrás de un camión: deja un hueco más largo.',
        ],
        players='1–4 jugadores',
    ),
    dict(
        title='Mina de Gemas',
        genre='party',
        tags=['laberinto', 'gemas', 'versus', 'vector'],
        orient='portrait', aspect='4:3', inputs='TKG',
        engine='maze',
        cfg=dict(mode='gemas', bg='#0a0912', help='Una mina a oscuras para 1–4: solo ves lo que alumbra tu farol, y el farol de los demás te delata a ti. Muévete con las flechas, el joystick o deslizando el dedo y recoge gemas: las azules valen 1, las rosas 3 y la dorada 5. Si chocas con un rival, el que más gemas lleve encima suelta la mitad por el suelo, así que conviene ir dejándolas en la vagoneta del centro de la mina, donde ya nadie te las puede quitar. Con A das un destello que ilumina toda la galería durante un momento, pero tarda ocho segundos en recargarse. Noventa segundos; gana quien más gemas haya guardado en la vagoneta.'),
        pad=dict(d='8', a='Farol', t=1),
        mp=(1, 4),
        desc=[
            'Mina de Gemas es una carrera a oscuras por una galería excavada al azar. Cada minero lleva un farol que apenas alumbra unas casillas alrededor, así que el laberinto se descubre a trozos y hay que memorizarlo sobre la marcha. Lo que ya has visto queda dibujado en penumbra, pero las gemas y los rivales solo se ven dentro de un halo de luz: por eso el farol es a la vez tu única forma de orientarte y la manera más fácil de que te encuentren.',
            'Las gemas salen repartidas por toda la galería y valen distinto según el color, de una a cinco. Mientras las llevas encima son tuyas a medias: si un rival te alcanza, el que más lleve suelta tres por el suelo y el otro puede recogerlas. Para asegurarlas hay que volver a la vagoneta de la entrada y descargarlas, con el riesgo de perder tiempo en el camino de vuelta. Esa tensión entre seguir recogiendo o ir a guardar es el corazón de la partida, y se nota más cuando quedan pocos segundos y alguien vuelve cargado.',
            'Pulsando A el farol alumbra el doble durante unos segundos, con una espera antes de poder repetirlo: muy útil para cruzar una zona desconocida o para localizar a quien va ganando. Cuando pasan los noventa segundos aparece la clasificación con las gemas guardadas de cada uno. Se juega en la tele con los móviles de mando o tú solo contra mineros de la CPU, que van a lo suyo y afinan su ruta cuando les ganas.',
        ],
        tips=[
            'No acumules: cada viaje a la vagoneta convierte gemas en puntos que ya nadie te quita.',
            'Si ves un farol acercarse por un pasillo estrecho y vas cargado, mejor dar la vuelta.',
            'Guarda el destello del farol para las galerías nuevas; a ciegas se pierde mucho tiempo.',
        ],
        players='1–4 jugadores',
    ),
]
