"""Oleada 3 — mesa: dominó por parejas (motor `domino`), damas chinas y ajedrez (motor `mesa`)."""
PAD_D = dict(d='h', a='Jugar', b='Otra punta', t=1)
PAD_M = dict(d='8', a='Elegir', b='Atrás', t=1)

GAMES = [
    dict(
        title='Dominó por Parejas', genre='strategy-cards', tags=['domino', 'parejas', 'mesa', 'bar', 'familia', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='domino', pad=PAD_D, mp=(1, 4), players='1–4 jugadores',
        cfg=dict(mode='parejas', target=50, help='Juegas con el de enfrente: J1 y J3 contra J2 y J4. La primera mano sale el que tiene el doble seis. En tu turno toca una ficha de tu mano: si casa por las dos puntas elige a cuál la pegas (◀ o ▶, o el botón B con el mando). Si tienes ficha que casa estás obligado a ponerla; solo se pasa cuando no casa ninguna y no hay pozo para robar. Quien se queda sin fichas hace dominó y su pareja se anota los puntos que quedan a los rivales; si se cierra la mano gana la pareja con menos puntos en la mano. Partida a 50 puntos.'),
        desc=[
            'El dominó de toda la vida, el de la mesa del bar con las fichas boca abajo y el golpe seco al colocar: cuatro jugadores repartidos en dos parejas, siete fichas cada uno del juego de doble seis y ni una sola ficha en el pozo. Se juega en el sentido de las agujas del reloj y el que abre la primera mano es quien tiene el doble seis, que está obligado a plantarlo en el centro. A partir de ahí la cadena crece por las dos puntas y cada uno va colocando la ficha que casa con el número de un extremo.',
            'La ley del arrastre es sagrada: si tienes una ficha que casa, la pones, aunque no te convenga. Solo se pasa cuando de verdad no tienes nada, y ese paso es información que todos ven, porque delata los números que te faltan. Ahí empieza el juego de verdad: tapar la punta que sabes que tu rival no puede seguir, dejarle la mesa cerrada a él y abierta a tu compañero, y guardar la ficha que manda para el final. Quien se queda sin fichas canta dominó y su pareja se apunta todo lo que queda en las manos contrarias; si nadie puede colocar, la mano se cierra y gana la pareja que menos puntos tenga, con desempate a favor de quien puso la última ficha.',
            'Sin tele juegas tú con tu mano a la vista y la CPU ocupa las otras tres sillas, incluida la de tu compañero: las fichas que no casan salen apagadas para que se aprenda el arrastre jugando. En la tele cada uno ve sus siete fichas solo en su móvil, con las jugables marcadas y un botón de paso cuando toca; la pantalla grande enseña la cadena, las dos puntas y cuántas fichas le quedan a cada uno. Las CPU recuerdan los pasos de los demás y juegan mejor cada vez que les ganas.',
        ],
        tips=['Cuenta los pasos: si un rival se ha quedado fuera del cuatro, deja las dos puntas a cuatros siempre que puedas.', 'No sueltes tus dobles a lo tonto; colócalos cuando aún te quedan fichas de ese número para poder seguir tú mismo.', 'Si vas a cerrar la mano, hazlo cuando tu pareja tenga pocos puntos en la mano: los tantos se cuentan y deciden la partida.'],
    ),
    dict(
        title='Damas Chinas', genre='strategy-cards', tags=['damas-chinas', 'estrella', 'canicas', 'saltos', 'familia', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='mesa', pad=PAD_M, mp=(1, 4), players='1–4 jugadores',
        cfg=dict(mode='damaschinas', help='Lleva tus seis canicas a la punta de enfrente, la que tiene tu color dibujado en los agujeros. Toca una canica tuya y luego el agujero donde quieres dejarla: puedes moverte a un agujero vecino libre o saltar por encima de una canica (de cualquiera) cayendo justo detrás, encadenando todos los saltos que quieras. Con el mando, A elige canica, las flechas recorren los destinos y A confirma; B cancela. No se puede terminar dentro de la punta de otro jugador, aunque sí atravesarla saltando, y una canica que ya está en su casa solo se mueve dentro de ella. Gana el primero que llena sus seis agujeros.'),
        desc=[
            'La estrella de seis puntas de siempre, en una versión rápida de seis canicas por jugador para que una partida entre en un rato. Cada uno sale de su punta y tiene que llevar todas sus canicas a la punta de enfrente, que aparece marcada con su color en el tablero. Lo bonito del juego no es avanzar de agujero en agujero, sino construir escaleras: una canica bien colocada sirve de trampolín, y un buen encadenado de saltos puede cruzar media estrella en un solo turno.',
            'Se salta por encima de cualquier canica, propia o ajena, cayendo siempre en el agujero inmediatamente posterior, que tiene que estar libre; y mientras siga habiendo saltos se puede seguir saltando en el mismo movimiento, cambiando de dirección todas las veces que haga falta. Nadie come ni pierde piezas: lo único que se disputa es el camino. Para que la partida no se atasque hay dos reglas clásicas: no se puede terminar un movimiento dentro de la punta de otro jugador, aunque sí atravesarla de un salto, y la canica que ya ha llegado a su casa no vuelve a salir de ella.',
            'Juegan de dos a cuatro: a dos se enfrentan las puntas opuestas, a tres se reparten alternas para que nadie tenga vecino y a cuatro se usan dos parejas de puntas enfrentadas. Sin tele juegas tú contra las CPU tocando la canica y el agujero; en la tele cada uno mueve desde su móvil con el joystick y el botón A, y el tablero grande enseña las canicas de cada color y cuántas lleva en casa. Las CPU empiezan bastante despistadas y afinan el camino a medida que les vas ganando.',
        ],
        tips=['Antes de mover mira si puedes encadenar dos o tres saltos: casi siempre hay una escalera mejor que el primer salto que ves.', 'No dejes rezagada la última canica; una sola atrás te cuesta muchos turnos al final, cuando ya no hay canicas para saltar.', 'Aprovecha las canicas de los rivales como trampolín: el pasillo central se llena y ahí es donde se hacen las cadenas largas.'],
    ),
    dict(
        title='Ajedrez de Salón', genre='strategy-cards', tags=['ajedrez', 'mesa', 'clasico', 'mate', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='mesa', pad=PAD_M, mp=(1, 2), players='1–2 jugadores',
        cfg=dict(mode='ajedrez', help='Ajedrez completo con todas las reglas: enroque corto y largo, captura al paso, coronación (eliges la pieza) y final por jaque mate, rey ahogado, repetición triple, regla de las 50 jugadas o material insuficiente. Toca tu pieza y luego la casilla de destino: los puntos verdes marcan los movimientos legales y los círculos rosas las capturas. Con el mando, las flechas mueven el cursor, A elige y confirma y B cancela. La CPU empieza en el nivel más bajo y sube un nivel cada vez que le ganas.'),
        desc=[
            'Ajedrez de verdad, con las reglas completas y sin atajos: las seis piezas con sus movimientos, el enroque corto y el largo con sus condiciones (rey y torre sin mover, casillas libres y sin pasar por jaque), la captura al paso, la coronación en la que eliges si quieres dama, torre, alfil o caballo, y todos los finales de partida, incluidos el rey ahogado, las tablas por repetición triple de la posición, la regla de las cincuenta jugadas y el material insuficiente. El generador de jugadas está verificado con perft, la prueba estándar que cuenta todas las partidas posibles hasta cierta profundidad y las compara con los números conocidos.',
            'La CPU no está aquí para humillar a nadie. En el nivel de salida mueve casi al buen tuntún entre las jugadas razonables, así que se le puede ganar la primera partida sin saber ninguna apertura; cada victoria tuya la sube un escalón, hasta cinco, y en los últimos niveles busca con poda alfa-beta, ordena las capturas y no deja piezas colgadas. El nivel queda guardado en tu navegador, de modo que la máquina se va ajustando a cómo juegas tú.',
            'El tablero se lee bien en el móvil: la última jugada queda resaltada, el rey en jaque se pinta en rojo, los destinos legales aparecen al tocar una pieza y un panel lateral lleva la cuenta de las piezas capturadas, la ventaja material y las jugadas de la regla de las cincuenta. En el modo tele podéis jugar dos personas desde sus móviles, con el tablero girado para las negras. Tocando una pieza y su destino, o con las flechas y A del mando, no hace falta saber notación para jugar.',
        ],
        tips=['Saca primero los caballos y los alfiles, enroca pronto y no muevas dos veces la misma pieza en la apertura.', 'Antes de mover, mira qué te ataca: la mayoría de las partidas se pierden por dejar una pieza colgada, no por una combinación brillante.', 'Si vas ganando de material, cambia piezas; si vas perdiendo, complica la posición y busca la repetición o el ahogado.'],
    ),
]
