"""Oleada 4 — mesa: tres en raya anidado (motor `board` ampliado) y mancala (motor `mancala`)."""
PAD_N = dict(d='8', a='Poner', b='', t=1)
PAD_S = dict(d='8', a='Sembrar', b='', t=1)

GAMES = [
    dict(
        title='Tres en Raya Anidado', genre='strategy-cards', tags=['tres-en-raya', 'tablero', 'tactica', 'versus', 'clasico', 'vector'],
        orient='portrait', aspect='4:3', inputs='TKMG', engine='board', pad=PAD_N, mp=(1, 2), players='1–2 jugadores',
        cfg=dict(mode='anidado', help='Nueve tres en raya pequeños dentro de uno grande. La casilla donde juegas decide en qué tablero pequeño juega el rival: si pones tu ficha en la esquina de arriba a la izquierda de un tablero, el otro tiene que jugar en el tablero de arriba a la izquierda. Ganar un tablero pequeño te da esa casilla del grande, y gana la partida quien haga tres tableros en línea. Si te mandan a un tablero ya terminado puedes jugar donde quieras. Los puntos marcan las casillas legales. Toca la casilla, o muévete con las flechas y confirma con A.'),
        desc=[
            'El tres en raya de siempre tiene un problema conocido: dos personas que sepan jugar empatan siempre. Esta versión lo arregla con una vuelta de tuerca que lo convierte en un juego de verdad. Hay nueve tableros pequeños colocados formando a su vez un tablero grande de tres por tres, y la regla que lo cambia todo es esta: la casilla que eliges dentro de un tablero pequeño decide a qué tablero pequeño mandas a tu rival. Si juegas en la casilla central de tu tablero, el otro está obligado a jugar en el tablero central. Si le mandas a un tablero que ya está ganado o lleno, entonces queda libre y puede colocar donde quiera, así que regalar esa libertad suele costar cara.',
            'Ganar un tablero pequeño no da la partida: da esa casilla del tablero grande, y la victoria es hacer tres tableros en línea, en fila, columna o diagonal. Eso obliga a pensar en dos capas a la vez. Una jugada puede ser magnífica en el tablero pequeño y pésima en el grande, porque manda al rival justo al sitio donde le conviene rematar. Aprender a jugar es, sobre todo, aprender a mirar dos casillas por delante: dónde quiero poner mi ficha y dónde acabará jugando el otro por culpa de esa ficha.',
            'La CPU busca con poda alfa-beta y empieza floja de verdad: en el nivel de salida se le gana sin saber nada, y cada victoria tuya la sube un escalón hasta tres, quedándose guardado en tu navegador. Los tres niveles de dificultad cambian cuánto piensa y cuánto se equivoca a propósito. En el modo tele juegan dos personas desde sus móviles con el joystick y el botón A, con el turno marcado en grande y los tableros legales resaltados para que nadie se pierda; la pantalla señala la última jugada y tacha con su color los tableros ya conquistados.',
        ],
        tips=['Antes de colocar, mira a qué tablero mandas al rival: una casilla buena que le regala un tablero ganador es una mala jugada.', 'Mandar a alguien a un tablero terminado le da carta blanca; guárdate ese recurso para cuando no tengas nada mejor.', 'Las esquinas del tablero grande valen mucho: entran en tres líneas y son las que deciden las partidas largas.'],
    ),
    dict(
        title='Mancala de Semillas', genre='strategy-cards', tags=['mancala', 'kalah', 'semillas', 'mesa', 'clasico', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='mancala', pad=PAD_S, mp=(1, 2), players='1–2 jugadores',
        cfg=dict(mode='kalah', help='Cada uno tiene seis hoyos con cuatro semillas y un granero al final de su fila. Toca uno de tus hoyos: coges todas sus semillas y las vas dejando de una en una en los hoyos siguientes, saltándote siempre el granero del rival. Si la última semilla cae justo en tu granero, repites turno. Si cae en un hoyo tuyo que estaba vacío, te llevas esa semilla y todas las del hoyo de enfrente. La partida acaba cuando alguien se queda sin semillas en su lado: el otro recoge las suyas y gana quien más tenga en el granero.'),
        desc=[
            'El mancala es probablemente el juego de tablero más antiguo que se sigue jugando, y esta es su versión más extendida: seis hoyos por jugador, cuatro semillas en cada uno y un granero al final de la fila. En tu turno coges todas las semillas de uno de tus hoyos y las vas sembrando de una en una en los hoyos siguientes, siempre en el mismo sentido, dejando una en tu granero al pasar por delante y saltándote el del contrario, que no es asunto tuyo. No hay dados ni cartas: toda la información está a la vista y todo lo que pasa depende de haber contado bien.',
            'Las dos reglas que hacen grande al juego son la del turno extra y la de la captura. Si la última semilla que siembras cae exactamente en tu granero, vuelves a jugar, y encadenar dos o tres turnos seguidos es lo que decide las partidas buenas. Si la última cae en un hoyo de tu lado que estaba vacío, te quedas con esa semilla y además con todas las del hoyo que tienes justo enfrente, así que una trampa bien preparada puede valer diez semillas de golpe. Cuando un jugador se queda sin nada que sembrar en su lado, la partida termina, el otro recoge todo lo que le queda y se cuentan los graneros.',
            'El tablero es de madera tallada, con los hoyos hundidos y las semillas repartiéndose una a una para que se pueda seguir la cuenta con la vista. Se adapta solo: en el móvil de pie las dos filas se ponen en columnas y en horizontal quedan como en la mesa. La CPU tiene tres niveles, empieza jugando casi de oído y sube un escalón cada vez que le ganas, quedando guardado en tu navegador; los tres ajustes de dificultad cambian además cuánto piensa. En el modo tele juegan dos personas desde sus móviles, cada una con sus flechas y el botón de sembrar.',
        ],
        tips=['Cuenta antes de mover: el hoyo que tiene exactamente las semillas justas para acabar en tu granero te regala otro turno.', 'Dejar un hoyo tuyo vacío es una trampa: si consigues que la última semilla caiga ahí, te llevas todo el hoyo de enfrente.', 'Vigila los hoyos llenos del rival; si va a dar la vuelta entera, a veces conviene vaciar el tuyo antes de que te lo capture.'],
    ),
]
