"""Oleada 5 — motor `tren`: tres juegos de trenes (puzle de vías, gestión de metro y fiesta en la tele)."""

PAD_V = dict(d='8', a='Poner vía', b='Cambiar pieza', t=1)
PAD_M = dict(d='8', a='Abrir metro', b='Cambiar línea', t=1)
PAD_C = dict(d='8', a='', b='', t=1)

GAMES = [
    dict(
        title='Vías del Valle', genre='puzzle', tags=['trenes', 'vias', 'logica', 'niveles', 'puzle', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='tren', pad=PAD_V, players='1 jugador',
        cfg=dict(mode='vias', help='Coloca tramos de vía en la rejilla para que la locomotora salga de la cochera, recoja los vagones <b>por orden</b> (1, 2, 3…) y termine en la estación. Toca una casilla libre para poner la pieza elegida; vuelve a tocarla para girarla y, tras la cuarta vuelta, para quitarla. La <b>vía</b> manda al tren en una dirección fija; el <b>cambio de agujas</b> alterna: la primera vez sale recto y la siguiente girando. Los cruces dejan pasar de largo, los túneles te llevan a su gemelo y las rocas descarrilan el tren. Cuando el plano esté listo pulsa Arrancar. Cada nivel tiene un mínimo de piezas: igualarlo es la mejor manera de pasarlo.'),
        desc=[
            'Vías del Valle es un puzle de trazado con veinte niveles escritos a mano, sin nada generado al azar. Cada uno te da un valle en miniatura con su cochera, sus vagones numerados, su estación y un puñado de piezas contadas; tú decides por dónde pasa la vía. La gracia está en que el tren no se conduce: una vez pulsas Arrancar hace exactamente lo que dice el plano que has dibujado, así que toda la partida ocurre antes, en la cabeza, y lo que ves después es la comprobación de si tenías razón. Fallar no castiga: el tren descarrila, te dice por qué con una frase concreta y vuelves al plano con todo puesto.',
            'Las reglas crecen nivel a nivel y siempre se presentan una a una. Primero solo hay vía recta y curva. Luego aparecen las rocas, que obligan a rodear; los cruces, que dejan pasar sin desviar y permiten que el recorrido se corte a sí mismo; los túneles, que teletransportan el tren a su gemelo manteniendo la dirección; y por último el cambio de agujas, la pieza que lo cambia todo, porque alterna entre salir recto y salir girando cada vez que el tren la pisa, y con ella se construyen bucles que pasan dos veces por el mismo sitio y salen por caminos distintos. El orden de los vagones es sagrado: pisar el tres antes que el dos descarrila.',
            'Cada nivel trae un mínimo de piezas calculado por un resolutor propio que prueba de verdad todos los trazados posibles, así que ese número no es una estimación: es el óptimo. Terminar con más piezas vale, y el nivel se da por superado igual, pero igualar el mínimo es el reto de fondo y el marcador lo premia. El progreso se guarda por dificultad, de manera que Fácil, Normal y Difícil llevan su propia cuenta de niveles desbloqueados, y al terminar el vigésimo el juego se da por completado de verdad, con final y todo. En Fácil se regalan un par de piezas de más para que quepan los rodeos.',
        ],
        tips=['Antes de tocar nada, sigue con el dedo el camino entero desde la cochera hasta la estación pasando por los vagones en orden: casi siempre solo hay una forma de encadenarlos.',
              'El cambio de agujas sirve para pasar dos veces por la misma casilla y salir por sitios distintos; si un nivel te da uno, es porque el recorrido tiene que cruzarse consigo mismo.',
              'Si el tren se queda dando vueltas, es que el trazado se ha cerrado en bucle: busca la casilla donde vuelve a entrar con la misma dirección y rómpela.'],
    ),
    dict(
        title='Metro en Hora Punta', genre='strategy-cards', tags=['metro', 'gestion', 'lineas', 'ciudad', 'semanas', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='tren', pad=PAD_M, players='1 jugador',
        cfg=dict(mode='metro', help='Eres quien decide por dónde pasa el metro. En el plano van apareciendo estaciones con forma de círculo, triángulo, cuadrado, estrella, rombo o cruz. Elige una línea de colores abajo y toca estaciones para unirlas en ese orden; tocar una que ya está en la línea la quita. Cada tramo gasta vía del presupuesto de la semana. Pulsa «Tren +» para poner un tren en la línea elegida y luego «Abrir metro» para empezar. Los viajeros esperan en el andén y van a la parada que tenga su forma; si una línea no llega, se bajan en un transbordo y siguen en otra. Si una estación se llena y sigue llena demasiado tiempo, colapsa y pierdes la semana. Lleva a los viajeros que pide el objetivo antes de que se acabe el tiempo.'),
        desc=[
            'Metro en Hora Punta es un juego de planificar y ver cómo se rompe tu plan. Tienes doce semanas escritas a mano, cada una con su plano de estaciones, su presupuesto de vía, sus trenes y su objetivo de viajeros, y lo único que haces es decidir qué se une con qué. Los viajeros no aparecen al azar: cada estación emite el suyo en un instante fijo y con un destino fijo, así que dos partidas iguales dan resultados iguales y la culpa de que la cosa se atasque es siempre tuya. Eso convierte cada semana en un problema con solución, no en una tirada de dados.',
            'El sistema es el clásico de formas: un viajero con forma de triángulo quiere bajarse en cualquier estación triangular. Si la línea en la que se sube llega a una, perfecto; si no, se baja en la primera estación donde esa línea se cruza con otra que sí llega y espera allí el transbordo. Por eso el hallazgo de la partida no suele ser una línea larga y bonita, sino un par de líneas cortas que se cortan en el sitio correcto. Los trenes tienen ocho plazas y van y vienen por su línea sin parar; poner un tren de más en la línea saturada rinde más que estirar el trazado un kilómetro.',
            'La presión la marcan los andenes. Cada estación aguanta una cola; si se pasa y sigue pasada demasiado tiempo, colapsa y la semana se pierde. El aro rojo que crece alrededor de una parada es el aviso de que te queda poco para arreglarlo, y arreglarlo casi siempre significa cambiar el plano en marcha, porque se puede seguir dibujando con el metro abierto. Cada semana tiene además su medalla: llevar viajeros de sobra, terminar sin desbordar ninguna estación o hacerlo con muy poca vía. Son doce medallas y una partida que termina de verdad al acabar la semana doce, no un incremental infinito.',
        ],
        tips=['Antes de estirar una línea, mira si te falta un tren: casi siempre rinde más un tren de más en la línea que ya tienes que otro kilómetro de vía.',
              'Haz que todas las líneas pasen por la misma estación céntrica: con un solo transbordo bien puesto, todas las formas quedan conectadas con todas.',
              'Si un andén empieza a acumular cola, no esperes al aro rojo: mete ahí mismo un tramo corto hacia la forma que están pidiendo y la cola se vacía sola.'],
    ),
    dict(
        title='Choque de Trenes', genre='party', tags=['trenes', 'multijugador', 'fiesta', 'reparto', 'modo-tele', 'vector'],
        orient='auto', aspect='fill', inputs='TKMG', engine='tren', pad=PAD_C, mp=(1, 4), players='1–4 jugadores',
        cfg=dict(mode='choque', help='Tu tren no para nunca: lo único que haces es decirle por dónde girar. Mantén el joystick (o las flechas) hacia donde quieras salir y en el siguiente cruce tomará ese desvío si existe; si no, sigue recto. En el tablero van apareciendo cajas del color de cada jugador: recoge las tuyas pasando por encima y llévalas a tu apeadero, el cuadrado de tu color en una esquina. Solo se puede llevar una caja a la vez. Si dos trenes se tocan, chocan: los dos pierden la carga y se quedan parados un par de segundos. Gana quien más entregas haga antes de que se acabe el tiempo.'),
        desc=[
            'Choque de Trenes es un juego de fiesta para la tele con una regla que se entiende en cinco segundos: tu tren avanza solo y tú únicamente eliges el desvío del próximo cruce. Todos los trenes comparten el mismo tablero de vías, así que las rutas se pisan constantemente y la mitad de la partida consiste en calcular si te da tiempo a pasar por el cruce antes que el vecino o si te conviene dar el rodeo. Como nadie puede frenar, no hay forma de esperar a que pase el otro: o cambias de camino o chocáis.',
            'Las cajas van apareciendo en los cruces del centro del tablero con el color de su dueño, y solo tú puedes recoger las tuyas. Se lleva una cada vez y hay que llevarla hasta el apeadero de tu color, en una esquina, así que cada entrega es un viaje de ida y vuelta por el tablero entero con los demás trenes cruzándose por medio. Si dos trenes se tocan, los dos pierden la carga y se quedan humeando un par de segundos, lo que convierte el choque en un arma: cortarle el paso a quien vuelve cargado cuesta lo mismo que hacer una entrega propia.',
            'Se juega solo contra la máquina o hasta cuatro personas desde sus móviles en el modo tele, y la máquina cubre las plazas libres y sustituye a quien se va a mitad de partida. Las rondas son cortas, de poco más de un minuto y medio, y terminan siempre en podio, así que encadenar revanchas es lo natural. Hay tres dificultades que cambian la velocidad de los trenes y lo bien que conducen las máquinas, y el marcador se lleva por entregas, que es lo único que cuenta.',
        ],
        tips=['Mantén el joystick pulsado hacia donde quieras salir antes de llegar al cruce: el desvío se toma en el cruce, no en mitad del tramo.',
              'Volver cargado por el borde del tablero es más lento pero mucho más seguro: los choques pasan casi siempre en los cruces del centro.',
              'Si un rival vuelve cargado hacia su esquina, vale la pena cruzarse en su camino: le quitas la entrega y solo pierdes dos segundos.'],
    ),
]
