/* Tableros a mano de serpent-grid (plan Friv, F3 · tanda 3). 20 niveles dibujados uno a uno:
 * ninguno se genera al azar y todos están verificados (BFS) — el tablero es conexo, no hay
 * callejones sin salida (toda casilla libre tiene al menos dos vecinas libres) y el objetivo
 * (llaves y puerta) siempre se puede alcanzar.
 *
 * TABLERO — 17 columnas × 13 filas. En vertical el motor gira el tablero 90° (13×17), así que
 * el mismo dibujo se juega igual en móvil tumbado o de pie.
 *
 *   #  muro                 .  suelo
 *   S  salida de la serpiente (mira hacia `d`)
 *   K  llave                E  puerta (cerrada hasta cumplir el objetivo)
 *
 * PARÁMETROS de cada nivel:
 *   name   rótulo del nivel
 *   tip    lo que enseña (se lee al empezar, una sola frase)
 *   spd    casillas por segundo al empezar
 *   ac     casillas por segundo que se gana por cada manzana comida
 *   go     objetivo: {eat: manzanas, len: longitud, keys: true (todas), exit: true (ir a la puerta)}
 *   sp     frutas especiales que pueden salir: 'gold' (dorada), 'berry' (arándano, frena),
 *          'shrink' (encoger), 'freeze' (congelar), 'dash' (acelerón)
 *   wrap   túneles: '' ninguno, 'x' laterales, 'y' arriba y abajo, 'xy' los cuatro
 *   d      dirección inicial ('right' en todos: siempre hay pista libre por delante)
 *   th     tema (0 pradera, 1 desierto, 2 nieve, 3 crepúsculo, 4 selva)
 *
 * Todo se multiplica luego por la dificultad elegida (k.D).
 */
const SNAKELV = {
  'serpent-grid': [
    /* ---- 1-5: se aprende a girar, la dorada, las columnas, el arándano y los túneles ---- */
    { /*  1 */ name: 'Primeros bocados', tip: 'Come 6 manzanas. Desliza o usa las flechas para girar.',
      spd: 3.2, ac: 0.05, go: { eat: 6 }, sp: [], wrap: '', d: 'right', th: 0, m: [
        '.................',
        '.................',
        '.................',
        '.................',
        '.................',
        '.................',
        '...S.............',
        '.................',
        '.................',
        '.................',
        '.................',
        '.................',
        '.................'] },
    { /*  2 */ name: 'Manzana dorada', tip: 'La manzana dorada vale más, pero dura poco.',
      spd: 3.4, ac: 0.05, go: { eat: 8 }, sp: ['gold'], wrap: '', d: 'right', th: 0, m: [
        '.................',
        '.................',
        '.................',
        '....#.......#....',
        '.................',
        '.................',
        '...S.............',
        '.................',
        '.................',
        '....#.......#....',
        '.................',
        '.................',
        '.................'] },
    { /*  3 */ name: 'Entre columnas', tip: 'Las piedras no se pueden morder: rodéalas.',
      spd: 3.6, ac: 0.05, go: { eat: 8 }, sp: ['gold'], wrap: '', d: 'right', th: 1, m: [
        '.................',
        '.................',
        '..#..#..#..#..#..',
        '.................',
        '.................',
        '..#..#..#..#..#..',
        '...S.............',
        '.................',
        '.................',
        '..#..#..#..#..#..',
        '.................',
        '.................',
        '..#..#..#..#..#..'] },
    { /*  4 */ name: 'Arándanos', tip: 'El arándano azul te frena unos segundos: úsalo para girar con calma.',
      spd: 3.8, ac: 0.06, go: { eat: 10 }, sp: ['gold', 'berry'], wrap: '', d: 'right', th: 1, m: [
        '.................',
        '.................',
        '..####.....####..',
        '.................',
        '.................',
        '..#...........#..',
        '..#...S.......#..',
        '..#...........#..',
        '.................',
        '.................',
        '..####.....####..',
        '.................',
        '.................'] },
    { /*  5 */ name: 'Túneles', tip: 'Los laterales están abiertos: sal por un lado y entra por el otro.',
      spd: 4.0, ac: 0.06, go: { eat: 10 }, sp: ['gold', 'berry'], wrap: 'x', d: 'right', th: 2, m: [
        '.................',
        '.......###.......',
        '.................',
        '..###.......###..',
        '.................',
        '.................',
        '...S.............',
        '.................',
        '.................',
        '..###.......###..',
        '.................',
        '.......###.......',
        '.................'] },
    /* ---- 6-10: llaves, puerta, encoger y pasillos ---- */
    { /*  6 */ name: 'Las llaves', tip: 'Recoge las dos llaves y la puerta del centro se abrirá.',
      spd: 3.8, ac: 0.05, go: { keys: true, exit: true }, sp: ['gold'], wrap: '', d: 'right', th: 2, m: [
        '.................',
        '..K...........K..',
        '.................',
        '....#.....#......',
        '...S.............',
        '.................',
        '.........E.......',
        '.................',
        '.................',
        '....#.....#......',
        '.................',
        '.................',
        '.................'] },
    { /*  7 */ name: 'Cerrojo doble', tip: 'Tres llaves y un muro por medio. Piensa el camino antes de girar.',
      spd: 4.0, ac: 0.05, go: { keys: true, exit: true }, sp: ['gold', 'berry'], wrap: '', d: 'right', th: 3, m: [
        '.................',
        '..K....#....K....',
        '.......#.........',
        '..###..#..###....',
        '.......#.........',
        '...S.............',
        '.......E.........',
        '.................',
        '.......#.........',
        '..###..#..###....',
        '.......#.........',
        '..K....#.........',
        '.................'] },
    { /*  8 */ name: 'Encoger', tip: 'La gota verde te quita cuatro trozos de cola. Guárdala para cuando aprietes.',
      spd: 4.2, ac: 0.06, go: { eat: 12 }, sp: ['gold', 'shrink'], wrap: '', d: 'right', th: 3, m: [
        '.................',
        '..####...####....',
        '.................',
        '...S.............',
        '..#...#####...#..',
        '..#...........#..',
        '..#...........#..',
        '..#...........#..',
        '..#...#####...#..',
        '.................',
        '.................',
        '..####...####....',
        '.................'] },
    { /*  9 */ name: 'Creciendo', tip: 'Come hasta tener 16 de largo y cruza entonces la puerta.',
      spd: 4.0, ac: 0.05, go: { len: 16, exit: true }, sp: ['gold', 'berry'], wrap: '', d: 'right', th: 4, m: [
        '.................',
        '..####.....####..',
        '.................',
        '...S.............',
        '....#.......#....',
        '....#.......#....',
        '....#...E...#....',
        '....#.......#....',
        '....#.......#....',
        '.................',
        '..####.....####..',
        '.................',
        '.................'] },
    { /* 10 */ name: 'Pasillos', tip: 'Cinco pasillos y dos túneles. No te metas donde no quepas.',
      spd: 4.4, ac: 0.06, go: { eat: 12 }, sp: ['gold', 'shrink'], wrap: 'x', d: 'right', th: 4, m: [
        '.................',
        '.###.###.###.###.',
        '.................',
        '.###.###.###.###.',
        '.................',
        '...S.............',
        '.###.###.###.###.',
        '.................',
        '.###.###.###.###.',
        '.................',
        '.###.###.###.###.',
        '.................',
        '.................'] },
    /* ---- 11-15: congelar, cuatro llaves, túneles dobles y acelerón ---- */
    { /* 11 */ name: 'Hielo', tip: 'El copo te deja quieto dos segundos y medio: aprovecha para colocarte.',
      spd: 4.6, ac: 0.06, go: { eat: 12 }, sp: ['gold', 'freeze', 'shrink'], wrap: '', d: 'right', th: 2, m: [
        '.................',
        '..#.#.#.#.#.#.#..',
        '.................',
        '.###.........###.',
        '.................',
        '..#.#.#.#.#.#.#..',
        '...S.............',
        '..#.#.#.#.#.#.#..',
        '.................',
        '.###.........###.',
        '.................',
        '..#.#.#.#.#.#.#..',
        '.................'] },
    { /* 12 */ name: 'Cuatro llaves', tip: 'Cuatro esquinas, cuatro llaves. La puerta está en el centro.',
      spd: 4.4, ac: 0.05, go: { keys: true, exit: true }, sp: ['gold', 'freeze'], wrap: '', d: 'right', th: 0, m: [
        '.................',
        '.K.............K.',
        '.................',
        '...###.....###...',
        '...S.............',
        '..#...........#..',
        '........E........',
        '..#...........#..',
        '.................',
        '...###.....###...',
        '.................',
        '.K.............K.',
        '.................'] },
    { /* 13 */ name: 'Doble túnel', tip: 'Ahora los cuatro lados están abiertos. Crece hasta 18 y sal por la puerta.',
      spd: 4.6, ac: 0.06, go: { len: 18, exit: true }, sp: ['gold', 'shrink'], wrap: 'xy', d: 'right', th: 3, m: [
        '.................',
        '....#########....',
        '....#.......#....',
        '....#.......#....',
        '.................',
        '.S.......E.......',
        '.................',
        '.................',
        '.................',
        '....#.......#....',
        '....#.......#....',
        '....#########....',
        '.................'] },
    { /* 14 */ name: 'Espinas', tip: 'Muchas piedras sueltas: mira dos casillas por delante.',
      spd: 4.8, ac: 0.06, go: { eat: 14 }, sp: ['gold', 'freeze', 'shrink'], wrap: '', d: 'right', th: 1, m: [
        '.................',
        '..#.#.#.#.#.#.#..',
        '..#.#.#.#.#.#.#..',
        '.................',
        '.#.#.#.#.#.#.#.#.',
        '.#.#.#.#.#.#.#.#.',
        '...S.............',
        '.#.#.#.#.#.#.#.#.',
        '.#.#.#.#.#.#.#.#.',
        '.................',
        '..#.#.#.#.#.#.#..',
        '..#.#.#.#.#.#.#..',
        '.................'] },
    { /* 15 */ name: 'Acelerón', tip: 'El rayo naranja te lanza a toda velocidad cuatro segundos. Da muchos puntos.',
      spd: 4.8, ac: 0.05, go: { keys: true, exit: true }, sp: ['gold', 'dash', 'shrink'], wrap: '', d: 'right', th: 4, m: [
        '.................',
        '....#.......#....',
        '....#.......#....',
        '...S.............',
        '..K.#.......#.K..',
        '....#.......#....',
        '....#...#...#....',
        '....#.......#....',
        '..K.#...E...#.K..',
        '.................',
        '....#.......#....',
        '....#.......#....',
        '.................'] },
    /* ---- 16-20: salas, rejilla, cinco llaves, carrera y el nido ---- */
    { /* 16 */ name: 'Las salas', tip: 'Cuatro salas con una sola boca. Entrar es fácil; salir, menos.',
      spd: 5.0, ac: 0.06, go: { len: 20, exit: true }, sp: ['gold', 'shrink', 'freeze'], wrap: '', d: 'right', th: 0, m: [
        '.................',
        '..#####...#####..',
        '..#...#...#...#..',
        '..#...#...#...#..',
        '..##.##...##.##..',
        '.................',
        '...S....E........',
        '.................',
        '..##.##...##.##..',
        '..#...#...#...#..',
        '..#...#...#...#..',
        '..#####...#####..',
        '.................'] },
    { /* 17 */ name: 'Rejilla', tip: 'Arriba y abajo hay túnel. Come 16 sin quedarte encerrado.',
      spd: 5.2, ac: 0.06, go: { eat: 16 }, sp: ['gold', 'dash', 'shrink'], wrap: 'y', d: 'right', th: 2, m: [
        '.................',
        '.#.#.#.#.#.#.#.#.',
        '.................',
        '.#.#.#.#.#.#.#.#.',
        '.................',
        '.#.#.#.#.#.#.#.#.',
        '...S.............',
        '.#.#.#.#.#.#.#.#.',
        '.................',
        '.#.#.#.#.#.#.#.#.',
        '.................',
        '.#.#.#.#.#.#.#.#.',
        '.................'] },
    { /* 18 */ name: 'Cinco llaves', tip: 'La quinta llave está en el patio del centro. Entra con sitio para salir.',
      spd: 5.2, ac: 0.05, go: { keys: true, exit: true }, sp: ['gold', 'freeze', 'shrink'], wrap: 'x', d: 'right', th: 3, m: [
        '..K...........K..',
        '.................',
        '..#####...#####..',
        '..#...........#..',
        '...S...........E.',
        '.....#.....#.....',
        '.....#..K..#.....',
        '.....#.....#.....',
        '..#...........#..',
        '..#...........#..',
        '..#####...#####..',
        '.................',
        '..K...........K..'] },
    { /* 19 */ name: 'Carrera', tip: 'Rápido y largo: 24 de cuerpo antes de cruzar. Los túneles son tu amigo.',
      spd: 5.6, ac: 0.07, go: { len: 24, exit: true }, sp: ['gold', 'dash', 'shrink', 'freeze'], wrap: 'x', d: 'right', th: 1, m: [
        '.................',
        '.###.###.###.###.',
        '.................',
        '.................',
        '.###.###.###.###.',
        '.S...............',
        '........E........',
        '.................',
        '.###.###.###.###.',
        '.................',
        '.................',
        '.###.###.###.###.',
        '.................'] },
    { /* 20 */ name: 'El nido del Prisma', tip: 'Remate: cuatro llaves, 22 de cuerpo y la puerta del nido. Suerte.',
      spd: 6.0, ac: 0.07, go: { keys: true, len: 22, exit: true }, sp: ['gold', 'dash', 'shrink', 'freeze'], wrap: 'xy', d: 'right', th: 3, m: [
        '..K...........K..',
        '.#.###.###.###.#.',
        '.................',
        '.###..#####..###.',
        '...S.............',
        '....#.......#....',
        '....#...E...#....',
        '....#.......#....',
        '.................',
        '.###..#####..###.',
        '.................',
        '.#.###.###.###.#.',
        '..K...........K..'] },
  ],
};
if (typeof module !== 'undefined' && module.exports) module.exports = SNAKELV;   /* verificación desde Node */
